import type {
  CommandEntry,
  HostConnection,
  Project,
  TerminalSession,
  Workflow,
} from "@/lib/domain/types";

export const MOCK_HOST_CONNECTIONS: HostConnection[] = [
  {
    id: "host-main",
    name: "Primary Linux host",
    host: "calvin@workstation",
    status: "connected",
    environment: "local",
    operatingSystem: "Ubuntu 24.04",
    connectionMethod: "local profile",
    workspaceRoot: "/home/calvin/projects",
    lastCheckedAt: "Just now",
    safetyChecks: [
      {
        id: "main-shell",
        label: "Shell access boundary",
        state: "pass",
        detail: "Local profile only; no remote execution is active.",
      },
      {
        id: "main-creds",
        label: "Credential storage",
        state: "warn",
        detail: "Credential save is disabled in this phase.",
      },
      {
        id: "main-network",
        label: "Network reachability",
        state: "pass",
        detail: "Available on the local workspace network.",
      },
    ],
  },
  {
    id: "host-lab",
    name: "Lab node",
    host: "calvin@lab-box",
    status: "connecting",
    environment: "lab",
    operatingSystem: "Debian 12",
    connectionMethod: "saved preset",
    workspaceRoot: "/srv/workspaces",
    lastCheckedAt: "2 minutes ago",
    safetyChecks: [
      {
        id: "lab-shell",
        label: "Shell access boundary",
        state: "warn",
        detail: "Connection preview only; no host pairing is active.",
      },
      {
        id: "lab-cred",
        label: "Credential handling",
        state: "warn",
        detail: "Save credentials action is disabled.",
      },
      {
        id: "lab-routing",
        label: "Routing scope",
        state: "pass",
        detail: "Represents a static local profile for UI design only.",
      },
    ],
  },
  {
    id: "host-remote",
    name: "Remote staging",
    host: "calvin@staging-node",
    status: "offline",
    environment: "remote",
    operatingSystem: "Fedora 40",
    connectionMethod: "manual setup",
    workspaceRoot: "/opt/staging",
    lastCheckedAt: "12 minutes ago",
    safetyChecks: [
      {
        id: "remote-shell",
        label: "SSH boundary",
        state: "blocked",
        detail: "SSH is intentionally out of scope for this phase.",
      },
      {
        id: "remote-secrets",
        label: "Secret storage",
        state: "blocked",
        detail: "No secret storage or credential vault is wired.",
      },
      {
        id: "remote-ops",
        label: "Remote execution",
        state: "blocked",
        detail: "Command actions remain disabled and local-only.",
      },
    ],
  },
];

export const MOCK_PROJECTS: Project[] = [
  {
    id: "terminalflow",
    name: "TerminalFlow",
    summary: "Mobile control plane for terminal-driven workflows.",
    path: "/home/calvin/projects/TerminalFlow",
    language: "TypeScript",
    hostId: "host-main",
    health: "ready",
    updatedAt: "Today, 9:12 AM",
    openFiles: 4,
  },
  {
    id: "signalops",
    name: "SignalOps",
    summary: "Ops dashboard for service checks and deploy notes.",
    path: "/home/calvin/projects/signalops",
    language: "Go",
    hostId: "host-main",
    health: "ready",
    updatedAt: "Yesterday",
    openFiles: 2,
  },
  {
    id: "edge-notes",
    name: "Edge Notes",
    summary: "Side project for lightweight note capture and search.",
    path: "/srv/workspaces/edge-notes",
    language: "Rust",
    hostId: "host-lab",
    health: "attention",
    updatedAt: "2 days ago",
    openFiles: 6,
  },
];

export const MOCK_SESSIONS: TerminalSession[] = [
  {
    id: "session-hub",
    title: "App shell review",
    projectId: "terminalflow",
    hostId: "host-main",
    state: "running",
    branch: "main",
    lastActivityAt: "Just now",
    cwd: "/home/calvin/projects/TerminalFlow",
    commandPreview: "pnpm typecheck",
    outputPreview: "Type-check is currently green.",
    startedAt: "14 min ago",
  },
  {
    id: "session-api",
    title: "API workspace prep",
    projectId: "signalops",
    hostId: "host-main",
    state: "idle",
    branch: "feature/session-notes",
    lastActivityAt: "8 minutes ago",
    cwd: "/home/calvin/projects/signalops",
    commandPreview: "git status --short",
    outputPreview: "Workspace is clean.",
    startedAt: "1 hr ago",
  },
  {
    id: "session-lab",
    title: "Lab node diagnostics",
    projectId: "edge-notes",
    hostId: "host-lab",
    state: "paused",
    branch: "debug/host-check",
    lastActivityAt: "2 hours ago",
    cwd: "/srv/workspaces/edge-notes",
    commandPreview: "cargo test",
    outputPreview: "Waiting on host connection.",
    startedAt: "3 hr ago",
  },
];

export const MOCK_COMMAND_ENTRIES: CommandEntry[] = [
  {
    id: "command-001",
    sessionId: "session-hub",
    command: "pnpm install",
    status: "completed",
    timestamp: "14 min ago",
    cwd: "/home/calvin/projects/TerminalFlow",
    output: "Dependencies are already in sync.",
  },
  {
    id: "command-002",
    sessionId: "session-hub",
    command: "npm run typecheck",
    status: "completed",
    timestamp: "12 min ago",
    cwd: "/home/calvin/projects/TerminalFlow",
    output: "No type errors found.",
  },
  {
    id: "command-003",
    sessionId: "session-hub",
    command: "pnpm dev",
    status: "draft",
    timestamp: "Now",
    cwd: "/home/calvin/projects/TerminalFlow",
    output: "Composer only. No command execution is active.",
  },
  {
    id: "command-101",
    sessionId: "session-api",
    command: "git status --short",
    status: "completed",
    timestamp: "8 minutes ago",
    cwd: "/home/calvin/projects/signalops",
    output: "Workspace is clean.",
  },
  {
    id: "command-102",
    sessionId: "session-api",
    command: "git branch --show-current",
    status: "completed",
    timestamp: "6 minutes ago",
    cwd: "/home/calvin/projects/signalops",
    output: "feature/session-notes",
  },
  {
    id: "command-201",
    sessionId: "session-lab",
    command: "cargo test",
    status: "blocked",
    timestamp: "2 hours ago",
    cwd: "/srv/workspaces/edge-notes",
    output: "Blocked on host connection; not executed here.",
  },
];

export const MOCK_WORKFLOWS: Workflow[] = [
  {
    id: "workflow-check",
    name: "Preflight checks",
    description: "Validate the workspace before any future workflow runner is introduced.",
    projectId: "terminalflow",
    trigger: {
      id: "trigger-check",
      kind: "manual",
      label: "Manual trigger",
      detail: "A planner-only trigger that starts from the builder surface.",
    },
    target: {
      id: "target-check",
      mode: "workspace",
      projectId: "terminalflow",
      hostId: "host-main",
      projectName: "TerminalFlow",
      hostName: "Primary Linux host",
      workspaceRoot: "/home/calvin/projects/TerminalFlow",
      detail: "Local workspace root on the primary host.",
    },
    state: "ready",
    steps: [
      {
        id: "step-check-1",
        kind: "check",
        title: "Type-check workspace",
        detail: "Runs a local type safety pass in the preview only.",
        commandPreview: "npm run typecheck",
        status: "ready",
      },
      {
        id: "step-check-2",
        kind: "check",
        title: "Run lint review",
        detail: "Shows the lint step that would follow a run if execution were active.",
        commandPreview: "npm run lint",
        status: "ready",
      },
      {
        id: "step-check-3",
        kind: "command",
        title: "Build app bundle",
        detail: "Represents the final build action in the static plan.",
        commandPreview: "npm run build",
        status: "ready",
      },
    ],
    lastRunAt: "Today, 8:41 AM",
    runPreview: {
      id: "preview-check",
      status: "ready",
      summary: "Three-step preflight plan ready for review.",
      expectedOutcome: "The plan would finish with a clean build if execution were enabled.",
      nextRun: "Manual only",
      steps: [
        {
          id: "preview-check-1",
          kind: "check",
          title: "Type-check workspace",
          detail: "Expected to pass in the static preview.",
          commandPreview: "npm run typecheck",
          status: "ready",
        },
        {
          id: "preview-check-2",
          kind: "check",
          title: "Run lint review",
          detail: "Shown as ready, but execution is inactive.",
          commandPreview: "npm run lint",
          status: "pending",
        },
        {
          id: "preview-check-3",
          kind: "command",
          title: "Build app bundle",
          detail: "Final step in the preview sequence.",
          commandPreview: "npm run build",
          status: "pending",
        },
      ],
      checks: [
        {
          id: "preview-check-safe-1",
          label: "Execution boundary",
          state: "pass",
          detail: "Run actions render as disabled controls only.",
        },
        {
          id: "preview-check-safe-2",
          label: "Local data only",
          state: "pass",
          detail: "All preview content is derived from typed mock data.",
        },
      ],
    },
    safetyChecks: [
      {
        id: "workflow-check-safe-1",
        label: "Execution boundary",
        state: "pass",
        detail: "This workflow is static and cannot execute commands yet.",
      },
      {
        id: "workflow-check-safe-2",
        label: "Save and schedule actions",
        state: "warn",
        detail: "Save, schedule, and deploy buttons render but remain inactive.",
      },
    ],
  },
  {
    id: "workflow-notes",
    name: "Update notes",
    description: "Prepare a preview of note collection and summary steps for the editor workspace.",
    projectId: "edge-notes",
    trigger: {
      id: "trigger-notes",
      kind: "schedule",
      label: "Scheduled trigger",
      detail: "A static schedule chip with no background job attached.",
      schedule: "Every weekday at 9:00 AM",
    },
    target: {
      id: "target-notes",
      mode: "project",
      projectId: "edge-notes",
      hostId: "host-lab",
      projectName: "Edge Notes",
      hostName: "Lab node",
      workspaceRoot: "/srv/workspaces/edge-notes",
      detail: "Project-scoped planning target for editorial work.",
    },
    state: "draft",
    steps: [
      {
        id: "step-notes-1",
        kind: "handoff",
        title: "Fetch workspace context",
        detail: "Represents a workspace read before any future runner exists.",
        commandPreview: "List recent files",
        status: "ready",
      },
      {
        id: "step-notes-2",
        kind: "note",
        title: "Preview files",
        detail: "Static inspection of the planned file set.",
        commandPreview: "Open selected markdown files",
        status: "pending",
      },
      {
        id: "step-notes-3",
        kind: "decision",
        title: "Summarize changes",
        detail: "A decision step that would assemble the workflow output.",
        commandPreview: "Draft summary",
        status: "pending",
      },
    ],
    lastRunAt: "Not run yet",
    runPreview: {
      id: "preview-notes",
      status: "preview",
      summary: "Draft workflow with a scheduled trigger and project-scoped target.",
      expectedOutcome: "Would gather context and summarize note edits if execution were active.",
      nextRun: "Weekdays at 9:00 AM",
      steps: [
        {
          id: "preview-notes-1",
          kind: "handoff",
          title: "Fetch workspace context",
          detail: "Static preview of the read-only handoff step.",
          commandPreview: "List recent files",
          status: "ready",
        },
        {
          id: "preview-notes-2",
          kind: "note",
          title: "Preview files",
          detail: "Interactive controls are not wired to a runtime.",
          commandPreview: "Open selected markdown files",
          status: "pending",
        },
        {
          id: "preview-notes-3",
          kind: "decision",
          title: "Summarize changes",
          detail: "Previewed as the final workflow output step.",
          commandPreview: "Draft summary",
          status: "pending",
        },
      ],
      checks: [
        {
          id: "preview-notes-safe-1",
          label: "Schedule inactive",
          state: "warn",
          detail: "A schedule can be viewed but not activated in this phase.",
        },
        {
          id: "preview-notes-safe-2",
          label: "No persistence",
          state: "pass",
          detail: "Nothing is saved or dispatched by the preview surface.",
        },
      ],
    },
    safetyChecks: [
      {
        id: "workflow-notes-safe-1",
        label: "Scheduling boundary",
        state: "warn",
        detail: "Scheduled workflows render but do not enqueue jobs.",
      },
      {
        id: "workflow-notes-safe-2",
        label: "Execution inactive",
        state: "pass",
        detail: "The plan remains a local planning surface only.",
      },
    ],
  },
  {
    id: "workflow-sync",
    name: "Session sync",
    description: "Mirror session context into a blocked run preview to show safety boundaries.",
    projectId: "signalops",
    trigger: {
      id: "trigger-sync",
      kind: "event",
      label: "Event trigger",
      detail: "Event-driven vocabulary for future integrations only.",
    },
    target: {
      id: "target-sync",
      mode: "host",
      projectId: "signalops",
      hostId: "host-main",
      projectName: "SignalOps",
      hostName: "Primary Linux host",
      workspaceRoot: "/home/calvin/projects/signalops",
      detail: "Host-scoped preview used to show blocked targeting.",
    },
    state: "blocked",
    steps: [
      {
        id: "step-sync-1",
        kind: "check",
        title: "Inspect session context",
        detail: "Static inspection step for the selected session surface.",
        commandPreview: "Read session summary",
        status: "blocked",
      },
      {
        id: "step-sync-2",
        kind: "decision",
        title: "Collect output",
        detail: "Blocked until a real workflow runner exists.",
        commandPreview: "Summarize session output",
        status: "blocked",
      },
      {
        id: "step-sync-3",
        kind: "handoff",
        title: "Queue follow-up",
        detail: "Queueing is not wired in this phase.",
        commandPreview: "Queue follow-up note",
        status: "blocked",
      },
    ],
    lastRunAt: "Yesterday, 5:14 PM",
    runPreview: {
      id: "preview-sync",
      status: "blocked",
      summary: "Blocked workflow preview that highlights the execution boundary.",
      expectedOutcome: "No runtime action is possible. The preview is informational only.",
      nextRun: "Not scheduled",
      steps: [
        {
          id: "preview-sync-1",
          kind: "check",
          title: "Inspect session context",
          detail: "Displays what the workflow would read.",
          commandPreview: "Read session summary",
          status: "blocked",
        },
        {
          id: "preview-sync-2",
          kind: "decision",
          title: "Collect output",
          detail: "Blocked by design because execution is inactive.",
          commandPreview: "Summarize session output",
          status: "blocked",
        },
        {
          id: "preview-sync-3",
          kind: "handoff",
          title: "Queue follow-up",
          detail: "Queueing remains out of scope.",
          commandPreview: "Queue follow-up note",
          status: "blocked",
        },
      ],
      checks: [
        {
          id: "preview-sync-safe-1",
          label: "Host execution",
          state: "blocked",
          detail: "Remote or host execution is not active yet.",
        },
        {
          id: "preview-sync-safe-2",
          label: "Queueing",
          state: "blocked",
          detail: "No queues or background jobs are added in this phase.",
        },
      ],
    },
    safetyChecks: [
      {
        id: "workflow-sync-safe-1",
        label: "Host execution",
        state: "blocked",
        detail: "The target host is shown for planning only.",
      },
      {
        id: "workflow-sync-safe-2",
        label: "Workflow runner",
        state: "blocked",
        detail: "A real runner is intentionally not wired up.",
      },
    ],
  },
];

export const MOCK_WORKSPACE = {
  name: "Calvin's workspace",
  root: "/home/calvin/projects",
  hostConnectionCount: MOCK_HOST_CONNECTIONS.length,
  connectedHosts: MOCK_HOST_CONNECTIONS.filter((host) => host.status === "connected")
    .length,
  projectCount: MOCK_PROJECTS.length,
  runningSessions: MOCK_SESSIONS.filter((session) => session.state === "running").length,
  workflowCount: MOCK_WORKFLOWS.length,
} as const;
