import type {
  AlertActionPreview,
  AlertReviewItem,
  CommandEntry,
  CommandSimulationSafetyCheck,
  HealthDashboardMetric,
  IntegrationActionPreview,
  IntegrationActivityEvent,
  IntegrationConnection,
  IntegrationPermissionScope,
  IntegrationProvider,
  IntegrationProviderCategory,
  IntegrationReviewFinding,
  IntegrationStatusSummary,
  HostConnection,
  Project,
  ProjectHealthSummary,
  ReadinessActionPreview,
  ReadinessCategory,
  ReadinessFinding,
  ReadinessScore,
  ReadinessReview,
  Notification,
  NotificationActivityEvent,
  NotificationCategory,
  NotificationPreferencePreview,
  WorkspaceReadinessSnapshot,
  SimulatedCommandPreset,
  TerminalSession,
  WorkflowRun,
  Workflow,
} from "@/lib/domain/types";
import type {
  MockAuthSession,
  SecretAccessPolicy,
  SecretActivityEvent,
  SecretCategory,
  SecretMetadata,
  User,
  Workspace,
  WorkspaceAccessReview,
  WorkspaceMember,
  WorkspaceMembership,
  WorkspacePermissionGroup,
} from "@/lib/auth/auth-types";

export const MOCK_USERS: User[] = [
  {
    id: "user-calvin",
    profile: {
      displayName: "Calvin Reed",
      email: "calvin@terminalflow.local",
      title: "Product engineer",
      avatarLabel: "CR",
    },
  },
];

export const MOCK_WORKSPACES: Workspace[] = [
  {
    id: "workspace-terminalflow",
    name: "TerminalFlow Core",
    slug: "terminalflow-core",
    summary: "Primary control plane workspace for local product work.",
    root: "/home/calvin/projects/TerminalFlow",
    boundaryNote: "Browser-local workspace boundary only.",
  },
  {
    id: "workspace-labs",
    name: "Labs Sandbox",
    slug: "labs-sandbox",
    summary: "Static sandbox for experimental surfaces and layout checks.",
    root: "/home/calvin/projects/terminalflow-labs",
    boundaryNote: "Used for mock membership and workspace selection only.",
  },
  {
    id: "workspace-preview",
    name: "Preview Review",
    slug: "preview-review",
    summary: "Read-only preview workspace for mobile UI validation.",
    root: "/srv/workspaces/preview-review",
    boundaryNote: "No backend session or remote execution is active.",
  },
];

export const MOCK_WORKSPACE_MEMBERSHIPS: WorkspaceMembership[] = [
  {
    workspaceId: "workspace-terminalflow",
    userId: "user-calvin",
    role: "owner",
    joinedAt: "3 months ago",
  },
  {
    workspaceId: "workspace-labs",
    userId: "user-calvin",
    role: "admin",
    joinedAt: "5 weeks ago",
  },
  {
    workspaceId: "workspace-preview",
    userId: "user-calvin",
    role: "viewer",
    joinedAt: "Today",
  },
];

export const MOCK_WORKSPACE_MEMBERS: WorkspaceMember[] = [
  {
    id: "member-calvin",
    workspaceId: "workspace-terminalflow",
    displayName: "Calvin Reed",
    email: "calvin@terminalflow.local",
    role: "owner",
    status: "active",
    joinedAt: "3 months ago",
    lastSeenAt: "Just now",
    permissionGroupIds: ["group-core-admin"],
  },
  {
    id: "member-aisha",
    workspaceId: "workspace-terminalflow",
    displayName: "Aisha Patel",
    email: "aisha@terminalflow.local",
    role: "admin",
    status: "active",
    joinedAt: "2 weeks ago",
    lastSeenAt: "4 hours ago",
    permissionGroupIds: ["group-core-editor"],
  },
  {
    id: "member-ron",
    workspaceId: "workspace-terminalflow",
    displayName: "Ron Vega",
    email: "ron@terminalflow.local",
    role: "viewer",
    status: "invited",
    joinedAt: "Pending",
    lastSeenAt: "Not yet active",
    permissionGroupIds: ["group-core-viewer"],
  },
];

export const MOCK_WORKSPACE_PERMISSION_GROUPS: WorkspacePermissionGroup[] = [
  {
    id: "group-core-admin",
    workspaceId: "workspace-terminalflow",
    title: "Core admin",
    summary: "Full workspace control for mock review only.",
    role: "owner",
    permissions: [
      {
        id: "perm-invite",
        key: "invite-members",
        label: "Invite members",
        summary: "Open a new invite preview for the workspace.",
        state: "review",
      },
      {
        id: "perm-role",
        key: "change-roles",
        label: "Change roles",
        summary: "Adjust role labels in the local review model.",
        state: "review",
      },
      {
        id: "perm-remove",
        key: "remove-members",
        label: "Remove members",
        summary: "Expose member removal as disabled UI only.",
        state: "blocked",
      },
    ],
  },
  {
    id: "group-core-editor",
    workspaceId: "workspace-terminalflow",
    title: "Workspace editor",
    summary: "Collaborator access with limited invite review.",
    role: "admin",
    permissions: [
      {
        id: "perm-projects",
        key: "edit-projects",
        label: "Edit projects",
        summary: "Inspect project-linked workspace data.",
        state: "allowed",
      },
      {
        id: "perm-workflows",
        key: "review-workflows",
        label: "Review workflows",
        summary: "View workflow permission scope in this phase.",
        state: "review",
      },
    ],
  },
  {
    id: "group-core-viewer",
    workspaceId: "workspace-terminalflow",
    title: "Read-only viewer",
    summary: "Visibility into surfaces without member management.",
    role: "viewer",
    permissions: [
      {
        id: "perm-read",
        key: "read-surfaces",
        label: "Read surfaces",
        summary: "Can inspect the mock access review panels.",
        state: "allowed",
      },
      {
        id: "perm-invite-preview",
        key: "invite-preview",
        label: "Invite preview",
        summary: "Invite actions render but stay disabled.",
        state: "blocked",
      },
    ],
  },
];

export const MOCK_WORKSPACE_ACCESS_REVIEWS: WorkspaceAccessReview[] = [
  {
    id: "review-terminalflow-core",
    workspaceId: "workspace-terminalflow",
    reviewedAt: "Today",
    reviewedBy: "Local mock reviewer",
    summary: "One viewer invite remains pending and all role changes are local previews only.",
    findings: [
      {
        id: "finding-1",
        title: "Pending viewer invite",
        detail: "Invite preview is present but disabled, so no real invite is issued.",
        severity: "warn",
      },
      {
        id: "finding-2",
        title: "Owner scope is local",
        detail: "The owner role only affects mock UI labels and review surfaces.",
        severity: "info",
      },
      {
        id: "finding-3",
        title: "Member removal is disabled",
        detail: "Removal controls render as simulated actions without side effects.",
        severity: "blocked",
      },
    ],
    notes: [
      {
        id: "note-1",
        title: "Review note",
        detail: "All member, invite, and role interactions are read-only mock surfaces.",
      },
      {
        id: "note-2",
        title: "Boundary note",
        detail: "No backend authorization or RBAC enforcement is active in this phase.",
      },
    ],
    invites: [
      {
        id: "invite-ron",
        email: "ron@terminalflow.local",
        role: "viewer",
        groupId: "group-core-viewer",
        status: "draft",
      },
    ],
  },
];

export const MOCK_AUTH_SESSION: MockAuthSession = {
  userId: "user-calvin",
  activeWorkspaceId: "workspace-terminalflow",
  signedInAt: "Just now",
};

export const MOCK_SECRET_CATEGORIES: SecretCategory[] = [
  {
    id: "category-deploy",
    title: "Deployment metadata",
    summary: "Workspace-scoped deployment notes and environment references.",
    provider: "mock-managed",
    scope: "workspace",
  },
  {
    id: "category-automation",
    title: "Automation metadata",
    summary: "Project automation labels used for local review only.",
    provider: "manual",
    scope: "project",
  },
  {
    id: "category-host",
    title: "Host profile metadata",
    summary: "Host-facing configuration notes without credential values.",
    provider: "local-note",
    scope: "host-profile",
  },
];

export const MOCK_SECRET_METADATA: SecretMetadata[] = [
  {
    id: "secret-deploy-note",
    label: "Deploy note",
    categoryId: "category-deploy",
    provider: "mock-managed",
    scope: "workspace",
    riskLevel: "medium",
    rotationState: "due",
    lastReviewedAt: "Today",
    lastUpdatedAt: "Yesterday",
    redactedValue: "••••••••",
    owner: "TerminalFlow Core",
  },
  {
    id: "secret-automation-tag",
    label: "Automation tag",
    categoryId: "category-automation",
    provider: "manual",
    scope: "project",
    riskLevel: "low",
    rotationState: "fresh",
    lastReviewedAt: "2 days ago",
    lastUpdatedAt: "2 days ago",
    redactedValue: "••••••••",
    owner: "SignalOps",
  },
  {
    id: "secret-host-note",
    label: "Host note",
    categoryId: "category-host",
    provider: "local-note",
    scope: "host-profile",
    riskLevel: "high",
    rotationState: "stale",
    lastReviewedAt: "Last week",
    lastUpdatedAt: "Last week",
    redactedValue: "••••••••",
    owner: "Primary Linux host",
  },
];

export const MOCK_SECRET_ACCESS_POLICIES: SecretAccessPolicy[] = [
  {
    id: "policy-vault-core",
    workspaceId: "workspace-terminalflow",
    title: "Vault read preview",
    summary: "Read access is limited to local mock workspace roles and never reveals secret material.",
    allowedRoles: ["owner", "admin"],
    findings: [
      {
        id: "policy-finding-1",
        title: "Redaction enforced",
        detail: "All secret records render with metadata and a redacted display only.",
        severity: "info",
      },
      {
        id: "policy-finding-2",
        title: "Rotate disabled",
        detail: "Rotation controls are visible but perform no secret action.",
        severity: "warn",
      },
      {
        id: "policy-finding-3",
        title: "No backend vault",
        detail: "The vault is metadata-only and stores no secret values locally.",
        severity: "blocked",
      },
    ],
  },
];

export const MOCK_SECRET_ACTIVITY_EVENTS: SecretActivityEvent[] = [
  {
    id: "activity-1",
    time: "Now",
    kind: "review",
    title: "Vault reviewed locally",
    detail: "Metadata cards were rendered from static records only.",
  },
  {
    id: "activity-2",
    time: "2 hours ago",
    kind: "policy",
    title: "Policy preview refreshed",
    detail: "Allowed roles and redaction warnings were updated in local state.",
  },
  {
    id: "activity-3",
    time: "Yesterday",
    kind: "rotation",
    title: "Rotation marked due",
    detail: "Rotation state is a mock status without secret material or key handling.",
  },
  {
    id: "activity-4",
    time: "Last week",
    kind: "redaction",
    title: "Value display redacted",
    detail: "Secret values remain hidden and never exist in storage for this phase.",
  },
];

export const MOCK_NOTIFICATION_CATEGORIES: NotificationCategory[] = [
  {
    id: "category-integration",
    title: "Integration alerts",
    summary: "Review provider-linked notifications and connection-adjacent notices.",
    source: "integration",
    note: "Source labels are local preview metadata only.",
  },
  {
    id: "category-workspace",
    title: "Workspace notices",
    summary: "Track team and workspace-level notices without delivery plumbing.",
    source: "workspace",
    note: "No backend event ingestion is active.",
  },
  {
    id: "category-system",
    title: "System updates",
    summary: "Surface local system and maintenance review items.",
    source: "system",
    note: "Notifications are browser-local only.",
  },
  {
    id: "category-review",
    title: "Alert review",
    summary: "Prioritized items that need inspection or escalation in mock form.",
    source: "review",
    note: "Review states are static records, not workflows.",
  },
];

export const MOCK_NOTIFICATION_PREFERENCE_PREVIEWS: NotificationPreferencePreview[] = [
  {
    id: "pref-in-app",
    label: "In-app alerts",
    summary: "Preview local-only notification cards inside TerminalFlow.",
    enabled: true,
    note: "No push delivery or inbox sync is configured.",
  },
  {
    id: "pref-integration",
    label: "Integration notices",
    summary: "Group provider-linked alerts in the notification center.",
    enabled: true,
    note: "Linked provider metadata stays static and local.",
  },
  {
    id: "pref-digest",
    label: "Digest preview",
    summary: "Show a summary-style preview for low-priority items.",
    enabled: false,
    note: "Email delivery and scheduled jobs are out of scope.",
  },
  {
    id: "pref-escalation",
    label: "Escalation preview",
    summary: "Mark critical review items for attention in the UI.",
    enabled: true,
    note: "Escalate remains a disabled review action only.",
  },
];

export const MOCK_NOTIFICATION_ACTIVITY_EVENTS: NotificationActivityEvent[] = [
  {
    id: "notif-activity-1",
    time: "Now",
    kind: "received",
    title: "Notification center loaded",
    detail: "All alert records are rendered from static local data.",
  },
  {
    id: "notif-activity-2",
    time: "7 minutes ago",
    kind: "reviewed",
    title: "Review queue inspected",
    detail: "Alert review items were surfaced without any backend ingestion.",
  },
  {
    id: "notif-activity-3",
    time: "18 minutes ago",
    kind: "status-changed",
    title: "Unread state noted",
    detail: "Unread and read states are visual-only metadata in this phase.",
  },
  {
    id: "notif-activity-4",
    time: "Yesterday",
    kind: "escalated",
    title: "Escalation preview surfaced",
    detail: "Escalate actions render as disabled controls for review only.",
  },
  {
    id: "notif-activity-5",
    time: "Last week",
    kind: "archived",
    title: "Archived item retained locally",
    detail: "Archive state is preserved only as a mock record.",
  },
];

export const MOCK_ALERT_REVIEW_ITEMS: AlertReviewItem[] = [
  {
    id: "alert-review-1",
    notificationId: "notification-repo-connectivity",
    title: "Repo Mirror connection review",
    summary: "Repository-linked alert needs a local inspection pass.",
    status: "open",
    severity: "high",
    detail: "The provider link is represented as static metadata and does not contain tokens or live provider state.",
    recommendation: "Open the provider-linked preview and verify the static details.",
  },
  {
    id: "alert-review-2",
    notificationId: "notification-chat-summary",
    title: "Team Chat summary pending",
    summary: "A workspace notice is waiting in the review queue.",
    status: "reviewing",
    severity: "medium",
    detail: "The review item exists only as a local card; no message provider or webhook is active.",
    recommendation: "Mark the item read after confirming the local summary text.",
  },
  {
    id: "alert-review-3",
    notificationId: "notification-system-maintenance",
    title: "Maintenance reminder",
    summary: "System update can be archived after inspection.",
    status: "resolved",
    severity: "low",
    detail: "This reminder is a static workspace notice and has no delivery pipeline behind it.",
    recommendation: "Archive the item if the note is no longer needed.",
  },
];

export const MOCK_ALERT_ACTION_PREVIEWS: AlertActionPreview[] = [
  {
    id: "action-mark-read",
    kind: "mark-read",
    label: "Mark read",
    detail: "Show the state change without mutating any backend record.",
    mode: "disabled",
  },
  {
    id: "action-snooze",
    kind: "snooze",
    label: "Snooze",
    detail: "Present a snooze preview with no scheduler or queue.",
    mode: "disabled",
  },
  {
    id: "action-resolve",
    kind: "resolve",
    label: "Resolve",
    detail: "Render resolve as a local review action only.",
    mode: "disabled",
  },
  {
    id: "action-archive",
    kind: "archive",
    label: "Archive",
    detail: "Archive is a static state marker and does not persist remotely.",
    mode: "disabled",
  },
  {
    id: "action-escalate",
    kind: "escalate",
    label: "Escalate",
    detail: "Escalate shows an alert-review preview without sending anything.",
    mode: "disabled",
  },
  {
    id: "action-open-provider",
    kind: "open-provider",
    label: "Open provider",
    detail: "Surface linked provider metadata only; no provider page is opened.",
    mode: "disabled",
  },
];

export const MOCK_NOTIFICATIONS: Notification[] = [
  {
    id: "notification-repo-connectivity",
    categoryId: "category-integration",
    title: "Repo Mirror connection looks stale",
    summary: "The repository-linked integration shows a local review warning.",
    detail: "Repo Mirror is represented as mock metadata and the alert points to a disabled open-provider action.",
    severity: "high",
    status: "unread",
    source: "integration",
    sourceLabel: "Repo Mirror provider",
    linkedProviderId: "provider-repo-mirror",
    linkedConnectionId: "connection-repo-mirror",
    linkedProviderLabel: "Repo Mirror",
    linkedConnectionLabel: "Connected in review mode",
    createdAt: "Now",
    updatedAt: "Now",
    activityEventIds: ["notif-activity-1", "notif-activity-2"],
    alertReviewItemIds: ["alert-review-1"],
    preferencePreviewIds: ["pref-in-app", "pref-integration"],
  },
  {
    id: "notification-chat-summary",
    categoryId: "category-workspace",
    title: "Team chat summary is pending",
    summary: "A workspace notice is waiting in the review queue.",
    detail: "The summary is static local data and may be marked read or snoozed in preview only.",
    severity: "medium",
    status: "read",
    source: "workspace",
    sourceLabel: "Workspace notice stream",
    createdAt: "7 minutes ago",
    updatedAt: "5 minutes ago",
    activityEventIds: ["notif-activity-2", "notif-activity-3"],
    alertReviewItemIds: ["alert-review-2"],
    preferencePreviewIds: ["pref-in-app", "pref-digest"],
  },
  {
    id: "notification-system-maintenance",
    categoryId: "category-system",
    title: "Maintenance window reminder",
    summary: "A local system reminder is ready to archive after review.",
    detail: "No push, email, or background delivery exists; this is a browser-only static notice.",
    severity: "low",
    status: "snoozed",
    source: "system",
    sourceLabel: "Local system notice",
    createdAt: "Yesterday",
    updatedAt: "2 hours ago",
    activityEventIds: ["notif-activity-4", "notif-activity-5"],
    alertReviewItemIds: ["alert-review-3"],
    preferencePreviewIds: ["pref-in-app", "pref-escalation"],
  },
  {
    id: "notification-review-escalation",
    categoryId: "category-review",
    title: "Critical review requires escalation preview",
    summary: "Alert review remains a static record with an escalated severity marker.",
    detail: "Escalation is local metadata only and does not trigger any delivery pipeline.",
    severity: "critical",
    status: "unread",
    source: "review",
    sourceLabel: "Alert review queue",
    createdAt: "Last week",
    updatedAt: "Now",
    activityEventIds: ["notif-activity-1", "notif-activity-4"],
    alertReviewItemIds: ["alert-review-1", "alert-review-3"],
    preferencePreviewIds: ["pref-in-app", "pref-escalation"],
  },
];

export const MOCK_HOST_CONNECTIONS: HostConnection[] = [
  {
    id: "host-main",
    name: "Primary Linux host",
    host: "calvin@workstation",
    status: "connected",
    environment: "local",
    operatingSystem: "Ubuntu 24.04",
    connectionMethod: "local profile",
    workspaceRoot: "/home/calvin/projects",
    lastCheckedAt: "Just now",
    safetyChecks: [
      {
        id: "main-shell",
        label: "Shell access boundary",
        state: "pass",
        detail: "Local profile only; no remote execution is active.",
      },
      {
        id: "main-creds",
        label: "Credential storage",
        state: "warn",
        detail: "Credential save is disabled in this phase.",
      },
      {
        id: "main-network",
        label: "Network reachability",
        state: "pass",
        detail: "Available on the local workspace network.",
      },
    ],
  },
  {
    id: "host-lab",
    name: "Lab node",
    host: "calvin@lab-box",
    status: "connecting",
    environment: "lab",
    operatingSystem: "Debian 12",
    connectionMethod: "saved preset",
    workspaceRoot: "/srv/workspaces",
    lastCheckedAt: "2 minutes ago",
    safetyChecks: [
      {
        id: "lab-shell",
        label: "Shell access boundary",
        state: "warn",
        detail: "Connection preview only; no host pairing is active.",
      },
      {
        id: "lab-cred",
        label: "Credential handling",
        state: "warn",
        detail: "Save credentials action is disabled.",
      },
      {
        id: "lab-routing",
        label: "Routing scope",
        state: "pass",
        detail: "Represents a static local profile for UI design only.",
      },
    ],
  },
  {
    id: "host-remote",
    name: "Remote staging",
    host: "calvin@staging-node",
    status: "offline",
    environment: "remote",
    operatingSystem: "Fedora 40",
    connectionMethod: "manual setup",
    workspaceRoot: "/opt/staging",
    lastCheckedAt: "12 minutes ago",
    safetyChecks: [
      {
        id: "remote-shell",
        label: "SSH boundary",
        state: "blocked",
        detail: "SSH is intentionally out of scope for this phase.",
      },
      {
        id: "remote-secrets",
        label: "Secret storage",
        state: "blocked",
        detail: "No secret storage or credential vault is wired.",
      },
      {
        id: "remote-ops",
        label: "Remote execution",
        state: "blocked",
        detail: "Command actions remain disabled and local-only.",
      },
    ],
  },
];

export const MOCK_PROJECTS: Project[] = [
  {
    id: "terminalflow",
    name: "TerminalFlow",
    summary: "Mobile control plane for terminal-driven workflows.",
    path: "/home/calvin/projects/TerminalFlow",
    language: "TypeScript",
    hostId: "host-main",
    health: "ready",
    updatedAt: "Today, 9:12 AM",
    openFiles: 4,
  },
  {
    id: "signalops",
    name: "SignalOps",
    summary: "Ops dashboard for service checks and deploy notes.",
    path: "/home/calvin/projects/signalops",
    language: "Go",
    hostId: "host-main",
    health: "ready",
    updatedAt: "Yesterday",
    openFiles: 2,
  },
  {
    id: "edge-notes",
    name: "Edge Notes",
    summary: "Side project for lightweight note capture and search.",
    path: "/srv/workspaces/edge-notes",
    language: "Rust",
    hostId: "host-lab",
    health: "attention",
    updatedAt: "2 days ago",
    openFiles: 6,
  },
];

export const MOCK_HEALTH_DASHBOARD_METRICS: HealthDashboardMetric[] = [
  {
    id: "metric-score",
    label: "Overall readiness",
    value: "84%",
    detail: "Local mock score derived from the static review model.",
    tone: "accent",
  },
  {
    id: "metric-blockers",
    label: "Blocking findings",
    value: "1",
    detail: "One item is tagged blocked and needs review-only attention.",
    tone: "warn",
  },
  {
    id: "metric-local-only",
    label: "Execution mode",
    value: "Local preview",
    detail: "No audits, telemetry, provider sync, or checks are active.",
    tone: "good",
  },
  {
    id: "metric-coverage",
    label: "Coverage",
    value: "7 areas",
    detail: "Workspace, project, host, workflow, integration, vault, and notifications are represented.",
    tone: "accent",
  },
];

export const MOCK_READINESS_SCORES: ReadinessScore[] = [
  {
    id: "score-overall",
    label: "Overall readiness",
    score: 84,
    status: "ready",
    detail: "Good shape overall with one blocked host-execution gap kept in preview mode.",
    note: "This aggregate score is a static mock value only.",
  },
  {
    id: "score-workspace",
    label: "Workspace readiness",
    score: 92,
    status: "ready",
    detail: "Workspace boundaries, roles, and local review surfaces are established.",
    note: "Workspace scope stays local to the browser.",
  },
  {
    id: "score-project",
    label: "Project readiness",
    score: 88,
    status: "ready",
    detail: "Project cards and dashboard cues are surfaced from static records.",
    note: "Project health remains a preview signal.",
  },
  {
    id: "score-host",
    label: "Host readiness",
    score: 76,
    status: "watch",
    detail: "Host details are present, but remote execution and pairing remain out of scope.",
    note: "Host status is preview metadata only.",
  },
  {
    id: "score-workflow",
    label: "Workflow readiness",
    score: 72,
    status: "watch",
    detail: "Workflow descriptions exist, but no runner or deployment logic is active.",
    note: "Workflow readiness cannot trigger runs in this phase.",
  },
  {
    id: "score-integration",
    label: "Integration readiness",
    score: 69,
    status: "watch",
    detail: "Integration previews are static and do not sync provider state.",
    note: "Provider state stays mocked locally.",
  },
  {
    id: "score-secrets",
    label: "Secrets and vault readiness",
    score: 81,
    status: "watch",
    detail: "Secret metadata and policy previews are visible without any secret values.",
    note: "Credential usage and secret access remain out of scope.",
  },
  {
    id: "score-notifications",
    label: "Notification readiness",
    score: 86,
    status: "ready",
    detail: "Notification cards and alert review items are ready for local inspection.",
    note: "Delivery plumbing is intentionally inactive.",
  },
];

export const MOCK_READINESS_FINDINGS: ReadinessFinding[] = [
  {
    id: "finding-host-execution",
    categoryId: "category-host",
    title: "Host execution is intentionally blocked",
    detail: "Remote execution, PTY access, SSH, and workflow runners remain unavailable in this phase.",
    severity: "blocked",
    preview: "Shows a disabled host execution gap for review only.",
  },
  {
    id: "finding-integration-sync",
    categoryId: "category-integration",
    title: "Provider sync is metadata-only",
    detail: "Integration status, permissions, and review items do not touch provider APIs or webhooks.",
    severity: "warn",
    preview: "Highlights the lack of live sync and ingestion.",
  },
  {
    id: "finding-secrets-usage",
    categoryId: "category-secrets",
    title: "Secret usage is not active",
    detail: "Vault records are redacted previews only and cannot reveal or store real credentials.",
    severity: "warn",
    preview: "Confirms credential material is not present.",
  },
  {
    id: "finding-notification-delivery",
    categoryId: "category-notification",
    title: "Notification delivery stays local",
    detail: "Push, email, and background delivery are not connected in this phase.",
    severity: "info",
    preview: "Keeps delivery and scheduling as disabled preview states.",
  },
];

export const MOCK_READINESS_ACTION_PREVIEWS: ReadinessActionPreview[] = [
  {
    id: "action-fix",
    kind: "fix",
    label: "Fix",
    detail: "Render a fix-it preview with no side effects or remote operations.",
    mode: "disabled",
  },
  {
    id: "action-run-audit",
    kind: "run-audit",
    label: "Run audit",
    detail: "Show the audit button in a disabled state only.",
    mode: "disabled",
  },
  {
    id: "action-refresh-checks",
    kind: "refresh-checks",
    label: "Refresh checks",
    detail: "Preview a refresh control without collecting telemetry or running checks.",
    mode: "disabled",
  },
  {
    id: "action-export-report",
    kind: "export-report",
    label: "Export report",
    detail: "Surface an export affordance that does not create or upload a report.",
    mode: "disabled",
  },
  {
    id: "action-open-issue",
    kind: "open-issue",
    label: "Open issue",
    detail: "Show an issue preview control with no tracker, sync, or issue creation.",
    mode: "disabled",
  },
];

export const MOCK_WORKSPACE_READINESS_SNAPSHOT: WorkspaceReadinessSnapshot = {
  id: "snapshot-terminalflow",
  title: "Workspace readiness snapshot",
  summary: "The workspace is ready for local review while execution and provider links remain disabled.",
  status: "watch",
  projectCount: 3,
  hostCount: 3,
  workflowCount: 3,
  integrationCount: 4,
  secretCount: 3,
  notificationCount: 4,
  note: "Counts reflect static records only and do not query any backend source.",
};

export const MOCK_READINESS_CATEGORIES: ReadinessCategory[] = [
  {
    id: "category-workspace",
    kind: "workspace",
    title: "Workspace readiness",
    summary: "Review workspace boundaries, role previews, and local-only access posture.",
    status: "ready",
    scoreId: "score-workspace",
    findingIds: [],
    actionPreviewIds: ["action-fix", "action-run-audit"],
    note: "The workspace is modeled as a browser-local review surface.",
  },
  {
    id: "category-project",
    kind: "project",
    title: "Project readiness",
    summary: "Summarize the project cards, paths, and health markers in one place.",
    status: "ready",
    scoreId: "score-project",
    findingIds: [],
    actionPreviewIds: ["action-refresh-checks", "action-export-report"],
    note: "Project health is informational only.",
  },
  {
    id: "category-host",
    kind: "host",
    title: "Host readiness",
    summary: "Expose host posture while keeping remote execution and SSH out of scope.",
    status: "watch",
    scoreId: "score-host",
    findingIds: ["finding-host-execution"],
    actionPreviewIds: ["action-fix", "action-open-issue"],
    note: "Host state is represented with static safety metadata.",
  },
  {
    id: "category-workflow",
    kind: "workflow",
    title: "Workflow readiness",
    summary: "Describe workflow state without runners, queues, or deployment logic.",
    status: "watch",
    scoreId: "score-workflow",
    findingIds: [],
    actionPreviewIds: ["action-refresh-checks", "action-open-issue"],
    note: "Workflow readiness does not trigger any execution.",
  },
  {
    id: "category-integration",
    kind: "integration",
    title: "Integration readiness",
    summary: "Track provider-linked surfaces while keeping sync and ingestion mocked.",
    status: "watch",
    scoreId: "score-integration",
    findingIds: ["finding-integration-sync"],
    actionPreviewIds: ["action-run-audit", "action-refresh-checks"],
    note: "Integration data stays static and local.",
  },
  {
    id: "category-secrets",
    kind: "secrets",
    title: "Secrets and vault readiness",
    summary: "Preview secret metadata, vault posture, and redaction rules without secret values.",
    status: "watch",
    scoreId: "score-secrets",
    findingIds: ["finding-secrets-usage"],
    actionPreviewIds: ["action-fix", "action-export-report"],
    note: "Credential usage is intentionally absent.",
  },
  {
    id: "category-notification",
    kind: "notification",
    title: "Notification readiness",
    summary: "Summarize notification posture and alert review items without delivery plumbing.",
    status: "ready",
    scoreId: "score-notifications",
    findingIds: ["finding-notification-delivery"],
    actionPreviewIds: ["action-open-issue", "action-export-report"],
    note: "Notification delivery is local-only preview metadata.",
  },
];

export const MOCK_READINESS_REVIEW: ReadinessReview = {
  id: "review-terminalflow",
  title: "TerminalFlow readiness review",
  summary: "Static review covering workspace, project, host, workflow, integration, vault, and notification posture.",
  updatedAt: "Just now",
  workspaceSnapshotId: "snapshot-terminalflow",
  scoreIds: [
    "score-overall",
    "score-workspace",
    "score-project",
    "score-host",
    "score-workflow",
    "score-integration",
    "score-secrets",
    "score-notifications",
  ],
  categoryIds: [
    "category-workspace",
    "category-project",
    "category-host",
    "category-workflow",
    "category-integration",
    "category-secrets",
    "category-notification",
  ],
  findingIds: [
    "finding-host-execution",
    "finding-integration-sync",
    "finding-secrets-usage",
    "finding-notification-delivery",
  ],
  actionPreviewIds: [
    "action-fix",
    "action-run-audit",
    "action-refresh-checks",
    "action-export-report",
    "action-open-issue",
  ],
};

export const MOCK_PROJECT_HEALTH_SUMMARY: ProjectHealthSummary = {
  id: "health-terminalflow",
  title: "Project health dashboard",
  summary: "Local-only control center for readiness, scorecards, and review findings.",
  updatedAt: "Just now",
  overallScoreId: "score-overall",
  metricIds: ["metric-score", "metric-blockers", "metric-local-only", "metric-coverage"],
  reviewId: "review-terminalflow",
  note: "All dashboard information is derived from the mock records in this file.",
};

export const MOCK_INTEGRATION_PROVIDER_CATEGORIES: IntegrationProviderCategory[] = [
  {
    id: "category-code-hosting",
    title: "Code hosting",
    summary: "Repository-connected surfaces for review only.",
    note: "Provider links are static metadata and never authenticate.",
  },
  {
    id: "category-chat",
    title: "Team chat",
    summary: "Workspace messaging previews without a delivery pipeline.",
    note: "Messages are not sent or ingested in this phase.",
  },
  {
    id: "category-automation",
    title: "Automation",
    summary: "Workflow-adjacent provider previews and policy notes.",
    note: "Automation is represented as read-only mock data.",
  },
];

export const MOCK_INTEGRATION_PERMISSION_SCOPES: IntegrationPermissionScope[] = [
  {
    id: "scope-read",
    key: "read:metadata",
    label: "Read metadata",
    summary: "Inspect provider labels and static review notes.",
    preview: "Read-only preview",
    riskNote: "No live provider data is read.",
  },
  {
    id: "scope-review",
    key: "review:workspace",
    label: "Review workspace",
    summary: "Show workspace-linked configuration for local inspection.",
    preview: "Review preview",
    riskNote: "Workspace access is not granted.",
  },
  {
    id: "scope-post",
    key: "post:status",
    label: "Post status",
    summary: "Display a status-posting intent as local metadata only.",
    preview: "Disabled post preview",
    riskNote: "No outbound messages are sent.",
  },
  {
    id: "scope-alert",
    key: "alerts:read",
    label: "Read alerts",
    summary: "Surface alert links and review metadata.",
    preview: "Alert preview",
    riskNote: "No alert stream or webhook is active.",
  },
  {
    id: "scope-run",
    key: "automation:run",
    label: "Run automation",
    summary: "Represent automation intent without execution.",
    preview: "Execution blocked",
    riskNote: "No runner or job queue exists in this phase.",
  },
  {
    id: "scope-report",
    key: "automation:report",
    label: "Report status",
    summary: "Show reporting intent in the mock review surface.",
    preview: "Report preview",
    riskNote: "No backend analytics or report export is active.",
  },
];

export const MOCK_INTEGRATION_REVIEW_FINDINGS: IntegrationReviewFinding[] = [
  {
    id: "integration-finding-sync",
    title: "Provider sync is disabled",
    detail: "Connection status is preview metadata and does not reflect a live provider session.",
    severity: "warn",
  },
  {
    id: "integration-finding-webhook",
    title: "Webhook ingestion is out of scope",
    detail: "Alerts and review items are local records only and do not arrive from a webhook.",
    severity: "info",
  },
  {
    id: "integration-finding-authorize",
    title: "Authorize control is simulated",
    detail: "Authorize and revoke actions are rendered as review-only controls with no effect.",
    severity: "blocked",
  },
];

export const MOCK_INTEGRATION_ACTIVITY_EVENTS: IntegrationActivityEvent[] = [
  {
    id: "integration-activity-1",
    time: "Now",
    kind: "review",
    title: "Catalog reviewed locally",
    detail: "Provider metadata is loaded from static records only.",
  },
  {
    id: "integration-activity-2",
    time: "10 minutes ago",
    kind: "scope",
    title: "Scope preview updated",
    detail: "Permission scope labels remain informational.",
  },
  {
    id: "integration-activity-3",
    time: "1 hour ago",
    kind: "status",
    title: "Connection status marked",
    detail: "Connection states are mock labels and do not reflect live APIs.",
  },
  {
    id: "integration-activity-4",
    time: "Yesterday",
    kind: "sync",
    title: "Sync preview skipped",
    detail: "Sync is intentionally disabled in this phase.",
  },
  {
    id: "integration-activity-5",
    time: "Last week",
    kind: "policy",
    title: "Policy review surfaced",
    detail: "Policy notes remain static and local-only.",
  },
];

export const MOCK_INTEGRATION_ACTION_PREVIEWS: IntegrationActionPreview[] = [
  {
    id: "integration-action-connect",
    kind: "connect",
    label: "Connect",
    detail: "Render a connect preview without authentication or provider access.",
    mode: "disabled",
  },
  {
    id: "integration-action-disconnect",
    kind: "disconnect",
    label: "Disconnect",
    detail: "Show a disconnect control that does not touch provider state.",
    mode: "disabled",
  },
  {
    id: "integration-action-reconnect",
    kind: "reconnect",
    label: "Reconnect",
    detail: "Present a reconnect action without any live handshake.",
    mode: "disabled",
  },
  {
    id: "integration-action-sync",
    kind: "sync",
    label: "Sync",
    detail: "Preview sync intent without network calls or ingestion.",
    mode: "disabled",
  },
  {
    id: "integration-action-authorize",
    kind: "authorize",
    label: "Authorize",
    detail: "Display authorization as a local review affordance only.",
    mode: "disabled",
  },
  {
    id: "integration-action-revoke",
    kind: "revoke",
    label: "Revoke",
    detail: "Keep revoke as a disabled review control.",
    mode: "disabled",
  },
];

export const MOCK_INTEGRATION_PROVIDERS: IntegrationProvider[] = [
  {
    id: "provider-repo-mirror",
    categoryId: "category-code-hosting",
    name: "Repo Mirror",
    summary: "Repository-linked provider preview for local review.",
    detail: "Repo Mirror represents a code-hosting integration as static metadata only.",
    workspaceNote: "Workspace-linked review surface only.",
    reviewSummary: "Sync, authorize, and revoke controls remain disabled.",
    connectionSummary: "Connection posture is a mock review state.",
    riskLevel: "medium",
    scopeIds: ["scope-read", "scope-review"],
  },
  {
    id: "provider-team-chat",
    categoryId: "category-chat",
    name: "Team Chat",
    summary: "Collaboration provider preview with no live delivery path.",
    detail: "Team Chat exists only as browser-local metadata and review copy.",
    workspaceNote: "Workspace notice surface only.",
    reviewSummary: "Messages and alerts remain simulated.",
    connectionSummary: "No real chat provider is connected.",
    riskLevel: "low",
    scopeIds: ["scope-read", "scope-post", "scope-alert"],
  },
  {
    id: "provider-build-relay",
    categoryId: "category-automation",
    name: "Build Relay",
    summary: "Automation provider preview for workflow-adjacent notes.",
    detail: "Build Relay describes automation posture without a runner or queue.",
    workspaceNote: "Automation review surface only.",
    reviewSummary: "Execution and reporting remain blocked.",
    connectionSummary: "Automation posture is static and read-only.",
    riskLevel: "high",
    scopeIds: ["scope-run", "scope-report"],
  },
];

export const MOCK_INTEGRATION_CONNECTIONS: IntegrationConnection[] = [
  {
    id: "connection-repo-mirror",
    providerId: "provider-repo-mirror",
    status: "reviewing",
    lastCheckedAt: "Just now",
    lastActivityAt: "5 minutes ago",
    riskNote: "Provider sync remains local-only metadata.",
    findingIds: ["integration-finding-sync"],
    activityEventIds: ["integration-activity-1", "integration-activity-3"],
    actionPreviewIds: ["integration-action-sync", "integration-action-authorize"],
  },
  {
    id: "connection-team-chat",
    providerId: "provider-team-chat",
    status: "connected",
    lastCheckedAt: "7 minutes ago",
    lastActivityAt: "15 minutes ago",
    riskNote: "Messaging stays mock-local and no delivery path is active.",
    findingIds: ["integration-finding-webhook"],
    activityEventIds: ["integration-activity-2", "integration-activity-5"],
    actionPreviewIds: ["integration-action-connect", "integration-action-disconnect"],
  },
  {
    id: "connection-build-relay",
    providerId: "provider-build-relay",
    status: "blocked",
    lastCheckedAt: "Yesterday",
    lastActivityAt: "Yesterday",
    riskNote: "Automation controls stay disabled in this phase.",
    findingIds: ["integration-finding-authorize"],
    activityEventIds: ["integration-activity-4"],
    actionPreviewIds: ["integration-action-reconnect", "integration-action-revoke"],
  },
];

export const MOCK_INTEGRATION_STATUS_SUMMARY: IntegrationStatusSummary = {
  totalProviders: MOCK_INTEGRATION_PROVIDERS.length,
  totalCategories: MOCK_INTEGRATION_PROVIDER_CATEGORIES.length,
  totalScopes: MOCK_INTEGRATION_PERMISSION_SCOPES.length,
  totalConnections: MOCK_INTEGRATION_CONNECTIONS.length,
};

export const MOCK_SESSIONS: TerminalSession[] = [
  {
    id: "session-hub",
    title: "App shell review",
    projectId: "terminalflow",
    hostId: "host-main",
    state: "running",
    branch: "main",
    lastActivityAt: "Just now",
    cwd: "/home/calvin/projects/TerminalFlow",
    commandPreview: "pnpm typecheck",
    outputPreview: "Type-check is currently green.",
    startedAt: "14 min ago",
  },
  {
    id: "session-api",
    title: "API workspace prep",
    projectId: "signalops",
    hostId: "host-main",
    state: "idle",
    branch: "feature/session-notes",
    lastActivityAt: "8 minutes ago",
    cwd: "/home/calvin/projects/signalops",
    commandPreview: "git status --short",
    outputPreview: "Workspace is clean.",
    startedAt: "1 hr ago",
  },
  {
    id: "session-lab",
    title: "Lab node diagnostics",
    projectId: "edge-notes",
    hostId: "host-lab",
    state: "paused",
    branch: "debug/host-check",
    lastActivityAt: "2 hours ago",
    cwd: "/srv/workspaces/edge-notes",
    commandPreview: "cargo test",
    outputPreview: "Waiting on host connection.",
    startedAt: "3 hr ago",
  },
];

export const MOCK_COMMAND_ENTRIES: CommandEntry[] = [
  {
    id: "command-001",
    sessionId: "session-hub",
    command: "pnpm install",
    status: "completed",
    timestamp: "14 min ago",
    cwd: "/home/calvin/projects/TerminalFlow",
    output: "Dependencies are already in sync.",
  },
  {
    id: "command-002",
    sessionId: "session-hub",
    command: "npm run typecheck",
    status: "completed",
    timestamp: "12 min ago",
    cwd: "/home/calvin/projects/TerminalFlow",
    output: "No type errors found.",
  },
  {
    id: "command-003",
    sessionId: "session-hub",
    command: "pnpm dev",
    status: "draft",
    timestamp: "Now",
    cwd: "/home/calvin/projects/TerminalFlow",
    output: "Composer only. No command execution is active.",
  },
  {
    id: "command-101",
    sessionId: "session-api",
    command: "git status --short",
    status: "completed",
    timestamp: "8 minutes ago",
    cwd: "/home/calvin/projects/signalops",
    output: "Workspace is clean.",
  },
  {
    id: "command-102",
    sessionId: "session-api",
    command: "git branch --show-current",
    status: "completed",
    timestamp: "6 minutes ago",
    cwd: "/home/calvin/projects/signalops",
    output: "feature/session-notes",
  },
  {
    id: "command-201",
    sessionId: "session-lab",
    command: "cargo test",
    status: "blocked",
    timestamp: "2 hours ago",
    cwd: "/srv/workspaces/edge-notes",
    output: "Blocked on host connection; not executed here.",
  },
];

const allowlistedSafetyCheck: CommandSimulationSafetyCheck = {
  id: "sim-safety-allowlisted",
  label: "Allowlisted mock command",
  state: "allowlisted",
  detail: "This command is handled by local static simulation only.",
};

const warningSafetyCheck: CommandSimulationSafetyCheck = {
  id: "sim-safety-warning",
  label: "Local simulation warning",
  state: "warning",
  detail: "The command is safe to preview, but the simulator is returning a cautionary mock state.",
};

const blockedSafetyCheck: CommandSimulationSafetyCheck = {
  id: "sim-safety-blocked",
  label: "Blocked by phase guard",
  state: "blocked",
  detail: "Host, shell, and workflow execution are intentionally out of scope for this phase.",
};

export const MOCK_SIMULATED_COMMAND_PRESETS: SimulatedCommandPreset[] = [
  {
    id: "preset-typecheck",
    label: "Type-check workspace",
    command: "npm run typecheck",
    description: "Allowed mock command that returns a clean local result.",
    status: "completed",
    summary: "The simulator reports a clean type-check with no shell execution.",
    exitCode: 0,
    duration: "1.4s",
    output: {
      stdout: ["> terminalflow@0.2.0 typecheck", "> tsc --noEmit", "No type errors found."],
      stderr: [],
    },
    safetyCheck: allowlistedSafetyCheck,
  },
  {
    id: "preset-status",
    label: "Inspect workspace status",
    command: "git status --short",
    description: "Local preview command that surfaces a cautionary mock state.",
    status: "warning",
    summary: "The simulator shows a warning-style status check with local-only output.",
    exitCode: 0,
    duration: "0.8s",
    output: {
      stdout: ["M app/(tabs)/sessions/[sessionId]/page.tsx", "?? components/session/command-composer.tsx"],
      stderr: ["Mock warning: workspace state is illustrative only."],
    },
    safetyCheck: warningSafetyCheck,
  },
  {
    id: "preset-lint",
    label: "Preview lint failure",
    command: "npm run lint",
    description: "Mock failure state for command review and UI testing.",
    status: "failed",
    summary: "The simulator returns a failed exit code and stderr-style output.",
    exitCode: 1,
    duration: "2.1s",
    output: {
      stdout: ["> terminalflow@0.2.0 lint", "> eslint ."],
      stderr: ["1 problem found in static preview mode."],
    },
    safetyCheck: warningSafetyCheck,
  },
  {
    id: "preset-ssh",
    label: "Blocked host probe",
    command: "ssh staging",
    description: "Intentionally blocked to show the safety explanation path.",
    status: "blocked",
    summary: "The simulator blocks this command and explains why before any result is shown.",
    exitCode: null,
    duration: "--",
    output: {
      stdout: [],
      stderr: [],
    },
    safetyCheck: blockedSafetyCheck,
  },
];

export const MOCK_WORKFLOWS: Workflow[] = [
  {
    id: "workflow-check",
    name: "Preflight checks",
    projectId: "terminalflow",
    trigger: "Manual",
    state: "ready",
    steps: ["typecheck", "lint", "build"],
    lastRunAt: "Today, 8:41 AM",
  },
  {
    id: "workflow-notes",
    name: "Update notes",
    projectId: "edge-notes",
    trigger: "Manual",
    state: "draft",
    steps: ["fetch workspace", "preview files", "summarize changes"],
    lastRunAt: "Not run yet",
  },
  {
    id: "workflow-sync",
    name: "Session sync",
    projectId: "signalops",
    trigger: "On demand",
    state: "blocked",
    steps: ["inspect session", "collect output", "queue follow-up"],
    lastRunAt: "Yesterday, 5:14 PM",
  },
];

export const MOCK_WORKFLOW_RUNS: WorkflowRun[] = [
  {
    id: "run-preflight-001",
    workflowId: "workflow-check",
    workflowName: "Preflight checks",
    projectId: "terminalflow",
    trigger: "Manual",
    target: "TerminalFlow on Primary Linux host",
    targetDetail: "Local workspace planning run only.",
    workspaceRoot: "/home/calvin/projects/TerminalFlow",
    status: "completed",
    safetyState: "safe",
    startTime: "Today, 8:41 AM",
    duration: "3m 42s",
    summary: "The static preflight run finished cleanly after the three planned steps.",
    steps: [
      {
        id: "run-preflight-001-step-1",
        stepId: "step-check-1",
        title: "Type-check workspace",
        kind: "check",
        status: "completed",
        startedAt: "8:41 AM",
        finishedAt: "8:42 AM",
        duration: "48s",
        detail: "Type-check completed with no errors.",
      },
      {
        id: "run-preflight-001-step-2",
        stepId: "step-check-2",
        title: "Run lint review",
        kind: "check",
        status: "completed",
        startedAt: "8:42 AM",
        finishedAt: "8:43 AM",
        duration: "1m 04s",
        detail: "Lint pass completed in preview mode.",
      },
      {
        id: "run-preflight-001-step-3",
        stepId: "step-check-3",
        title: "Build app bundle",
        kind: "command",
        status: "completed",
        startedAt: "8:43 AM",
        finishedAt: "8:45 AM",
        duration: "1m 50s",
        detail: "Build step ended cleanly in the static log surface.",
      },
    ],
    timeline: [
      {
        id: "run-preflight-001-event-1",
        kind: "started",
        time: "8:41 AM",
        title: "Run started",
        detail: "Manual trigger selected from the static builder.",
        index: 1,
      },
      {
        id: "run-preflight-001-event-2",
        kind: "step-started",
        time: "8:41 AM",
        title: "Type-check workspace started",
        detail: "The first workflow step moved into the active lane.",
        stepId: "run-preflight-001-step-1",
        index: 2,
      },
      {
        id: "run-preflight-001-event-3",
        kind: "step-finished",
        time: "8:42 AM",
        title: "Type-check workspace completed",
        detail: "No errors were recorded in the static execution log.",
        stepId: "run-preflight-001-step-1",
        index: 3,
      },
      {
        id: "run-preflight-001-event-4",
        kind: "step-started",
        time: "8:42 AM",
        title: "Run lint review started",
        detail: "Second step previewed as the run advanced.",
        stepId: "run-preflight-001-step-2",
        index: 4,
      },
      {
        id: "run-preflight-001-event-5",
        kind: "step-finished",
        time: "8:43 AM",
        title: "Run lint review completed",
        detail: "Lint review returned to the completed lane.",
        stepId: "run-preflight-001-step-2",
        index: 5,
      },
      {
        id: "run-preflight-001-event-6",
        kind: "step-started",
        time: "8:43 AM",
        title: "Build app bundle started",
        detail: "Build step entered the final phase of the run.",
        stepId: "run-preflight-001-step-3",
        index: 6,
      },
      {
        id: "run-preflight-001-event-7",
        kind: "completed",
        time: "8:45 AM",
        title: "Run completed",
        detail: "Workflow execution is static; this completion state is mock data only.",
        index: 7,
      },
    ],
    logs: [
      {
        id: "run-preflight-001-log-1",
        time: "8:41 AM",
        level: "info",
        stream: "stdout",
        message: "Starting preflight checks in static preview mode.",
      },
      {
        id: "run-preflight-001-log-2",
        time: "8:41 AM",
        level: "stdout",
        stream: "stdout",
        message: "[step 1] npm run typecheck",
        stepId: "run-preflight-001-step-1",
      },
      {
        id: "run-preflight-001-log-3",
        time: "8:42 AM",
        level: "stdout",
        stream: "stdout",
        message: "[step 1] No type errors found.",
        stepId: "run-preflight-001-step-1",
      },
      {
        id: "run-preflight-001-log-4",
        time: "8:42 AM",
        level: "stdout",
        stream: "stdout",
        message: "[step 2] npm run lint",
        stepId: "run-preflight-001-step-2",
      },
      {
        id: "run-preflight-001-log-5",
        time: "8:43 AM",
        level: "stdout",
        stream: "stdout",
        message: "[step 3] npm run build",
        stepId: "run-preflight-001-step-3",
      },
      {
        id: "run-preflight-001-log-6",
        time: "8:45 AM",
        level: "info",
        stream: "stdout",
        message: "Static run marked completed. No workflow runner was used.",
      },
    ],
  },
  {
    id: "run-preflight-002",
    workflowId: "workflow-check",
    workflowName: "Preflight checks",
    projectId: "terminalflow",
    trigger: "Manual",
    target: "TerminalFlow on Primary Linux host",
    targetDetail: "Same run target, interrupted after safety review.",
    workspaceRoot: "/home/calvin/projects/TerminalFlow",
    status: "cancelled",
    safetyState: "warning",
    startTime: "Yesterday, 4:02 PM",
    duration: "1m 12s",
    summary: "The static run was cancelled after a safety interruption was surfaced.",
    steps: [
      {
        id: "run-preflight-002-step-1",
        stepId: "step-check-1",
        title: "Type-check workspace",
        kind: "check",
        status: "completed",
        startedAt: "4:02 PM",
        finishedAt: "4:03 PM",
        duration: "44s",
        detail: "Initial validation completed before interruption.",
      },
      {
        id: "run-preflight-002-step-2",
        stepId: "step-check-2",
        title: "Run lint review",
        kind: "check",
        status: "cancelled",
        startedAt: "4:03 PM",
        finishedAt: "4:03 PM",
        duration: "0s",
        detail: "Stopped because the run was cancelled in static preview.",
      },
      {
        id: "run-preflight-002-step-3",
        stepId: "step-check-3",
        title: "Build app bundle",
        kind: "command",
        status: "queued",
        startedAt: "Not started",
        finishedAt: "Not started",
        duration: "--",
        detail: "Never reached because the run was cancelled.",
      },
    ],
    timeline: [
      {
        id: "run-preflight-002-event-1",
        kind: "started",
        time: "4:02 PM",
        title: "Run started",
        detail: "Manual rerun launched from the workflow detail surface.",
        index: 1,
      },
      {
        id: "run-preflight-002-event-2",
        kind: "step-started",
        time: "4:02 PM",
        title: "Type-check workspace started",
        detail: "First step advanced normally.",
        stepId: "run-preflight-002-step-1",
        index: 2,
      },
      {
        id: "run-preflight-002-event-3",
        kind: "step-finished",
        time: "4:03 PM",
        title: "Type-check workspace completed",
        detail: "Static log captured the first step completion.",
        stepId: "run-preflight-002-step-1",
        index: 3,
      },
      {
        id: "run-preflight-002-event-4",
        kind: "interrupted",
        time: "4:03 PM",
        title: "Safety interruption",
        detail: "The run was paused and then cancelled in the mock timeline.",
        index: 4,
      },
      {
        id: "run-preflight-002-event-5",
        kind: "cancelled",
        time: "4:03 PM",
        title: "Run cancelled",
        detail: "No further steps were scheduled after cancellation.",
        index: 5,
      },
    ],
    logs: [
      {
        id: "run-preflight-002-log-1",
        time: "4:02 PM",
        level: "info",
        stream: "stdout",
        message: "Run resumed from history for static inspection.",
      },
      {
        id: "run-preflight-002-log-2",
        time: "4:03 PM",
        level: "warn",
        stream: "stderr",
        message: "Safety interruption surfaced; the run will not continue.",
      },
      {
        id: "run-preflight-002-log-3",
        time: "4:03 PM",
        level: "error",
        stream: "stderr",
        message: "Cancellation recorded in static state only.",
      },
    ],
  },
  {
    id: "run-sync-001",
    workflowId: "workflow-sync",
    workflowName: "Session sync",
    projectId: "signalops",
    trigger: "On demand",
    target: "SignalOps on Primary Linux host",
    targetDetail: "Blocked preview target showing a safety stop.",
    workspaceRoot: "/home/calvin/projects/signalops",
    status: "blocked",
    safetyState: "blocked",
    startTime: "Today, 9:08 AM",
    duration: "26s",
    summary: "The sync run was blocked at the safety boundary before any command-like activity.",
    steps: [
      {
        id: "run-sync-001-step-1",
        stepId: "step-sync-1",
        title: "Inspect session context",
        kind: "check",
        status: "blocked",
        startedAt: "9:08 AM",
        finishedAt: "9:08 AM",
        duration: "12s",
        detail: "Blocked before the session context could be collected.",
      },
      {
        id: "run-sync-001-step-2",
        stepId: "step-sync-2",
        title: "Collect output",
        kind: "decision",
        status: "blocked",
        startedAt: "Not started",
        finishedAt: "Not started",
        duration: "--",
        detail: "Blocked by the static safety guard.",
      },
      {
        id: "run-sync-001-step-3",
        stepId: "step-sync-3",
        title: "Queue follow-up",
        kind: "handoff",
        status: "queued",
        startedAt: "Not started",
        finishedAt: "Not started",
        duration: "--",
        detail: "Queued only in appearance; no background job exists.",
      },
    ],
    timeline: [
      {
        id: "run-sync-001-event-1",
        kind: "started",
        time: "9:08 AM",
        title: "Run started",
        detail: "Static blocked run entered the timeline.",
        index: 1,
      },
      {
        id: "run-sync-001-event-2",
        kind: "step-started",
        time: "9:08 AM",
        title: "Inspect session context started",
        detail: "The first step attempted to begin.",
        stepId: "run-sync-001-step-1",
        index: 2,
      },
      {
        id: "run-sync-001-event-3",
        kind: "interrupted",
        time: "9:08 AM",
        title: "Safety boundary reached",
        detail: "Host execution is not active, so the run was blocked.",
        index: 3,
      },
      {
        id: "run-sync-001-event-4",
        kind: "cancelled",
        time: "9:08 AM",
        title: "Run blocked",
        detail: "No workflow runner or queue handled the event.",
        index: 4,
      },
    ],
    logs: [
      {
        id: "run-sync-001-log-1",
        time: "9:08 AM",
        level: "info",
        stream: "stdout",
        message: "Session sync preview opened in static mode.",
      },
      {
        id: "run-sync-001-log-2",
        time: "9:08 AM",
        level: "warn",
        stream: "stderr",
        message: "Host execution inactive; blocking further progress.",
        stepId: "run-sync-001-step-1",
      },
      {
        id: "run-sync-001-log-3",
        time: "9:08 AM",
        level: "error",
        stream: "stderr",
        message: "No runner, queue, or background job is attached.",
      },
    ],
  },
];

export const MOCK_WORKSPACE = {
  name: "Calvin's workspace",
  root: "/home/calvin/projects",
  hostConnectionCount: MOCK_HOST_CONNECTIONS.length,
  connectedHosts: MOCK_HOST_CONNECTIONS.filter((host) => host.status === "connected")
    .length,
  projectCount: MOCK_PROJECTS.length,
  runningSessions: MOCK_SESSIONS.filter((session) => session.state === "running").length,
  workflowCount: MOCK_WORKFLOWS.length,
  workflowRunCount: MOCK_WORKFLOW_RUNS.length,
} as const;
