import type {
  CommandEntry,
  CommandSimulationSafetyCheck,
  IntegrationActionPreview,
  IntegrationActivityEvent,
  IntegrationConnection,
  IntegrationPermissionScope,
  IntegrationProvider,
  IntegrationProviderCategory,
  IntegrationReviewFinding,
  HostConnection,
  Project,
  SimulatedCommandPreset,
  TerminalSession,
  WorkflowRun,
  Workflow,
} from "@/lib/domain/types";
import type {
  MockAuthSession,
  SecretAccessPolicy,
  SecretActivityEvent,
  SecretCategory,
  SecretMetadata,
  User,
  Workspace,
  WorkspaceAccessReview,
  WorkspaceMember,
  WorkspaceMembership,
  WorkspacePermissionGroup,
} from "@/lib/auth/auth-types";

export const MOCK_USERS: User[] = [
  {
    id: "user-calvin",
    profile: {
      displayName: "Calvin Reed",
      email: "calvin@terminalflow.local",
      title: "Product engineer",
      avatarLabel: "CR",
    },
  },
];

export const MOCK_WORKSPACES: Workspace[] = [
  {
    id: "workspace-terminalflow",
    name: "TerminalFlow Core",
    slug: "terminalflow-core",
    summary: "Primary control plane workspace for local product work.",
    root: "/home/calvin/projects/TerminalFlow",
    boundaryNote: "Browser-local workspace boundary only.",
  },
  {
    id: "workspace-labs",
    name: "Labs Sandbox",
    slug: "labs-sandbox",
    summary: "Static sandbox for experimental surfaces and layout checks.",
    root: "/home/calvin/projects/terminalflow-labs",
    boundaryNote: "Used for mock membership and workspace selection only.",
  },
  {
    id: "workspace-preview",
    name: "Preview Review",
    slug: "preview-review",
    summary: "Read-only preview workspace for mobile UI validation.",
    root: "/srv/workspaces/preview-review",
    boundaryNote: "No backend session or remote execution is active.",
  },
];

export const MOCK_WORKSPACE_MEMBERSHIPS: WorkspaceMembership[] = [
  {
    workspaceId: "workspace-terminalflow",
    userId: "user-calvin",
    role: "owner",
    joinedAt: "3 months ago",
  },
  {
    workspaceId: "workspace-labs",
    userId: "user-calvin",
    role: "admin",
    joinedAt: "5 weeks ago",
  },
  {
    workspaceId: "workspace-preview",
    userId: "user-calvin",
    role: "viewer",
    joinedAt: "Today",
  },
];

export const MOCK_WORKSPACE_MEMBERS: WorkspaceMember[] = [
  {
    id: "member-calvin",
    workspaceId: "workspace-terminalflow",
    displayName: "Calvin Reed",
    email: "calvin@terminalflow.local",
    role: "owner",
    status: "active",
    joinedAt: "3 months ago",
    lastSeenAt: "Just now",
    permissionGroupIds: ["group-core-admin"],
  },
  {
    id: "member-aisha",
    workspaceId: "workspace-terminalflow",
    displayName: "Aisha Patel",
    email: "aisha@terminalflow.local",
    role: "admin",
    status: "active",
    joinedAt: "2 weeks ago",
    lastSeenAt: "4 hours ago",
    permissionGroupIds: ["group-core-editor"],
  },
  {
    id: "member-ron",
    workspaceId: "workspace-terminalflow",
    displayName: "Ron Vega",
    email: "ron@terminalflow.local",
    role: "viewer",
    status: "invited",
    joinedAt: "Pending",
    lastSeenAt: "Not yet active",
    permissionGroupIds: ["group-core-viewer"],
  },
];

export const MOCK_WORKSPACE_PERMISSION_GROUPS: WorkspacePermissionGroup[] = [
  {
    id: "group-core-admin",
    workspaceId: "workspace-terminalflow",
    title: "Core admin",
    summary: "Full workspace control for mock review only.",
    role: "owner",
    permissions: [
      {
        id: "perm-invite",
        key: "invite-members",
        label: "Invite members",
        summary: "Open a new invite preview for the workspace.",
        state: "review",
      },
      {
        id: "perm-role",
        key: "change-roles",
        label: "Change roles",
        summary: "Adjust role labels in the local review model.",
        state: "review",
      },
      {
        id: "perm-remove",
        key: "remove-members",
        label: "Remove members",
        summary: "Expose member removal as disabled UI only.",
        state: "blocked",
      },
    ],
  },
  {
    id: "group-core-editor",
    workspaceId: "workspace-terminalflow",
    title: "Workspace editor",
    summary: "Collaborator access with limited invite review.",
    role: "admin",
    permissions: [
      {
        id: "perm-projects",
        key: "edit-projects",
        label: "Edit projects",
        summary: "Inspect project-linked workspace data.",
        state: "allowed",
      },
      {
        id: "perm-workflows",
        key: "review-workflows",
        label: "Review workflows",
        summary: "View workflow permission scope in this phase.",
        state: "review",
      },
    ],
  },
  {
    id: "group-core-viewer",
    workspaceId: "workspace-terminalflow",
    title: "Read-only viewer",
    summary: "Visibility into surfaces without member management.",
    role: "viewer",
    permissions: [
      {
        id: "perm-read",
        key: "read-surfaces",
        label: "Read surfaces",
        summary: "Can inspect the mock access review panels.",
        state: "allowed",
      },
      {
        id: "perm-invite-preview",
        key: "invite-preview",
        label: "Invite preview",
        summary: "Invite actions render but stay disabled.",
        state: "blocked",
      },
    ],
  },
];

export const MOCK_WORKSPACE_ACCESS_REVIEWS: WorkspaceAccessReview[] = [
  {
    id: "review-terminalflow-core",
    workspaceId: "workspace-terminalflow",
    reviewedAt: "Today",
    reviewedBy: "Local mock reviewer",
    summary: "One viewer invite remains pending and all role changes are local previews only.",
    findings: [
      {
        id: "finding-1",
        title: "Pending viewer invite",
        detail: "Invite preview is present but disabled, so no real invite is issued.",
        severity: "warn",
      },
      {
        id: "finding-2",
        title: "Owner scope is local",
        detail: "The owner role only affects mock UI labels and review surfaces.",
        severity: "info",
      },
      {
        id: "finding-3",
        title: "Member removal is disabled",
        detail: "Removal controls render as simulated actions without side effects.",
        severity: "blocked",
      },
    ],
    notes: [
      {
        id: "note-1",
        title: "Review note",
        detail: "All member, invite, and role interactions are read-only mock surfaces.",
      },
      {
        id: "note-2",
        title: "Boundary note",
        detail: "No backend authorization or RBAC enforcement is active in this phase.",
      },
    ],
    invites: [
      {
        id: "invite-ron",
        email: "ron@terminalflow.local",
        role: "viewer",
        groupId: "group-core-viewer",
        status: "draft",
      },
    ],
  },
];

export const MOCK_AUTH_SESSION: MockAuthSession = {
  userId: "user-calvin",
  activeWorkspaceId: "workspace-terminalflow",
  signedInAt: "Just now",
};

export const MOCK_SECRET_CATEGORIES: SecretCategory[] = [
  {
    id: "category-deploy",
    title: "Deployment metadata",
    summary: "Workspace-scoped deployment notes and environment references.",
    provider: "mock-managed",
    scope: "workspace",
  },
  {
    id: "category-automation",
    title: "Automation metadata",
    summary: "Project automation labels used for local review only.",
    provider: "manual",
    scope: "project",
  },
  {
    id: "category-host",
    title: "Host profile metadata",
    summary: "Host-facing configuration notes without credential values.",
    provider: "local-note",
    scope: "host-profile",
  },
];

export const MOCK_SECRET_METADATA: SecretMetadata[] = [
  {
    id: "secret-deploy-note",
    label: "Deploy note",
    categoryId: "category-deploy",
    provider: "mock-managed",
    scope: "workspace",
    riskLevel: "medium",
    rotationState: "due",
    lastReviewedAt: "Today",
    lastUpdatedAt: "Yesterday",
    redactedValue: "••••••••",
    owner: "TerminalFlow Core",
  },
  {
    id: "secret-automation-tag",
    label: "Automation tag",
    categoryId: "category-automation",
    provider: "manual",
    scope: "project",
    riskLevel: "low",
    rotationState: "fresh",
    lastReviewedAt: "2 days ago",
    lastUpdatedAt: "2 days ago",
    redactedValue: "••••••••",
    owner: "SignalOps",
  },
  {
    id: "secret-host-note",
    label: "Host note",
    categoryId: "category-host",
    provider: "local-note",
    scope: "host-profile",
    riskLevel: "high",
    rotationState: "stale",
    lastReviewedAt: "Last week",
    lastUpdatedAt: "Last week",
    redactedValue: "••••••••",
    owner: "Primary Linux host",
  },
];

export const MOCK_SECRET_ACCESS_POLICIES: SecretAccessPolicy[] = [
  {
    id: "policy-vault-core",
    workspaceId: "workspace-terminalflow",
    title: "Vault read preview",
    summary: "Read access is limited to local mock workspace roles and never reveals secret material.",
    allowedRoles: ["owner", "admin"],
    findings: [
      {
        id: "policy-finding-1",
        title: "Redaction enforced",
        detail: "All secret records render with metadata and a redacted display only.",
        severity: "info",
      },
      {
        id: "policy-finding-2",
        title: "Rotate disabled",
        detail: "Rotation controls are visible but perform no secret action.",
        severity: "warn",
      },
      {
        id: "policy-finding-3",
        title: "No backend vault",
        detail: "The vault is metadata-only and stores no secret values locally.",
        severity: "blocked",
      },
    ],
  },
];

export const MOCK_SECRET_ACTIVITY_EVENTS: SecretActivityEvent[] = [
  {
    id: "activity-1",
    time: "Now",
    kind: "review",
    title: "Vault reviewed locally",
    detail: "Metadata cards were rendered from static records only.",
  },
  {
    id: "activity-2",
    time: "2 hours ago",
    kind: "policy",
    title: "Policy preview refreshed",
    detail: "Allowed roles and redaction warnings were updated in local state.",
  },
  {
    id: "activity-3",
    time: "Yesterday",
    kind: "rotation",
    title: "Rotation marked due",
    detail: "Rotation state is a mock status without secret material or key handling.",
  },
  {
    id: "activity-4",
    time: "Last week",
    kind: "redaction",
    title: "Value display redacted",
    detail: "Secret values remain hidden and never exist in storage for this phase.",
  },
];

export const MOCK_INTEGRATION_PROVIDER_CATEGORIES: IntegrationProviderCategory[] = [
  {
    id: "category-code",
    title: "Code surfaces",
    summary: "Review metadata for repository and code-review integrations without live API access.",
    note: "Static connector previews only.",
  },
  {
    id: "category-collaboration",
    title: "Collaboration surfaces",
    summary: "Coordinate mock chat, issue, and task providers in a local-only catalog.",
    note: "Actions never leave the browser.",
  },
  {
    id: "category-knowledge",
    title: "Knowledge surfaces",
    summary: "Browse documentation and knowledge providers as read-only review cards.",
    note: "Permission scopes are preview metadata only.",
  },
  {
    id: "category-design",
    title: "Design surfaces",
    summary: "Show design handoff and review providers with safety notes and disabled actions.",
    note: "No provider SDKs or webhook receivers are used.",
  },
];

export const MOCK_INTEGRATION_PERMISSION_SCOPES: IntegrationPermissionScope[] = [
  {
    id: "scope-repo-read",
    key: "repo:read",
    label: "Repository read preview",
    summary: "Inspect repository metadata, branch names, and review summaries only.",
    preview: "Read-only metadata preview.",
    riskNote: "No token exchange or repo API calls are active.",
  },
  {
    id: "scope-repo-comments",
    key: "repo:comments",
    label: "Review comment preview",
    summary: "Show comment and review-note permissions as local UI metadata.",
    preview: "Comment surfaces render disabled.",
    riskNote: "No webhook listeners or write actions are available.",
  },
  {
    id: "scope-chat-read",
    key: "chat:read",
    label: "Chat read preview",
    summary: "Display channel and message scopes as static catalog data.",
    preview: "Messages stay in mock records.",
    riskNote: "No messaging provider API calls are made.",
  },
  {
    id: "scope-docs-read",
    key: "docs:read",
    label: "Docs read preview",
    summary: "Review document scopes for local-only knowledge surfaces.",
    preview: "Documents are not synchronized.",
    riskNote: "No sync jobs, refresh tokens, or storage are wired.",
  },
  {
    id: "scope-design-read",
    key: "design:read",
    label: "Design read preview",
    summary: "Show design file access as an inspection-only scope.",
    preview: "Design cards stay read-only.",
    riskNote: "No provider SDK or design API usage is added.",
  },
];

export const MOCK_INTEGRATION_REVIEW_FINDINGS: IntegrationReviewFinding[] = [
  {
    id: "finding-integrations-1",
    title: "No live OAuth",
    detail: "Provider sign-in is represented only as mock UI and never launches real authorization.",
    severity: "blocked",
  },
  {
    id: "finding-integrations-2",
    title: "Scopes are preview metadata",
    detail: "Permission scopes explain intended access but do not grant or store access.",
    severity: "info",
  },
  {
    id: "finding-integrations-3",
    title: "Actions are disabled",
    detail: "Connect, disconnect, reconnect, sync, authorize, and revoke controls are inert.",
    severity: "warn",
  },
  {
    id: "finding-integrations-4",
    title: "No backend connections",
    detail: "The catalog is local-only and does not call provider APIs or background workers.",
    severity: "blocked",
  },
];

export const MOCK_INTEGRATION_ACTIVITY_EVENTS: IntegrationActivityEvent[] = [
  {
    id: "integration-activity-1",
    time: "Now",
    kind: "review",
    title: "Catalog loaded locally",
    detail: "Integration metadata was rendered from static records only.",
  },
  {
    id: "integration-activity-2",
    time: "5 minutes ago",
    kind: "scope",
    title: "Scope preview inspected",
    detail: "Permission scopes were shown as read-only metadata cards.",
  },
  {
    id: "integration-activity-3",
    time: "12 minutes ago",
    kind: "status",
    title: "Connection status reviewed",
    detail: "Connection states remain local review markers with no live provider state.",
  },
  {
    id: "integration-activity-4",
    time: "Yesterday",
    kind: "sync",
    title: "Sync preview masked",
    detail: "Sync and authorize actions are rendered but do not invoke any backend workflow.",
  },
  {
    id: "integration-activity-5",
    time: "Last week",
    kind: "policy",
    title: "Boundary note refreshed",
    detail: "The integrations phase remains scoped to mock records and disabled actions.",
  },
];

export const MOCK_INTEGRATION_ACTION_PREVIEWS: IntegrationActionPreview[] = [
  {
    id: "integration-action-connect",
    kind: "connect",
    label: "Connect",
    detail: "Render a connection preview without initiating OAuth.",
    mode: "disabled",
  },
  {
    id: "integration-action-disconnect",
    kind: "disconnect",
    label: "Disconnect",
    detail: "Show disconnect review state without removing any real token or record.",
    mode: "disabled",
  },
  {
    id: "integration-action-reconnect",
    kind: "reconnect",
    label: "Reconnect",
    detail: "Present a reconnect preview only.",
    mode: "disabled",
  },
  {
    id: "integration-action-sync",
    kind: "sync",
    label: "Sync",
    detail: "Surface sync review actions without running jobs.",
    mode: "disabled",
  },
  {
    id: "integration-action-authorize",
    kind: "authorize",
    label: "Authorize",
    detail: "Display the authorize step as a local-only control.",
    mode: "disabled",
  },
  {
    id: "integration-action-revoke",
    kind: "revoke",
    label: "Revoke",
    detail: "Render revoke review controls but do not touch credentials.",
    mode: "disabled",
  },
];

export const MOCK_INTEGRATION_PROVIDERS: IntegrationProvider[] = [
  {
    id: "provider-repo-mirror",
    name: "Repo Mirror",
    categoryId: "category-code",
    summary: "Static repository review surface for local code metadata.",
    detail:
      "The Repo Mirror provider shows branch, review, and repository scope previews without any GitHub OAuth, provider API calls, or token storage.",
    connectionId: "connection-repo-mirror",
    riskLevel: "medium",
    scopeIds: ["scope-repo-read", "scope-repo-comments"],
    workspaceNote: "Code surface for the current workspace only.",
    connectionSummary: "Connected in review mode with no live provider session.",
    reviewSummary:
      "Repository metadata is represented as local cards and disabled actions only.",
  },
  {
    id: "provider-team-chat",
    name: "Team Chat",
    categoryId: "category-collaboration",
    summary: "Mock collaboration provider with message and channel preview scopes.",
    detail:
      "Team Chat surfaces channel visibility, message scope previews, and sync notes entirely from local records.",
    connectionId: "connection-team-chat",
    riskLevel: "high",
    scopeIds: ["scope-chat-read"],
    workspaceNote: "Read-only collaboration review surface.",
    connectionSummary: "Reviewing connection metadata; no chat API integration is active.",
    reviewSummary:
      "Chat permissions are metadata-only and do not expose conversations or credentials.",
  },
  {
    id: "provider-docs-index",
    name: "Docs Index",
    categoryId: "category-knowledge",
    summary: "Documentation and knowledge provider preview with local safety notes.",
    detail:
      "Docs Index models document permissions and review findings without cloud sync or backend storage.",
    connectionId: "connection-docs-index",
    riskLevel: "low",
    scopeIds: ["scope-docs-read"],
    workspaceNote: "Knowledge provider review for static docs only.",
    connectionSummary: "Offline preview status with no sync jobs or refresh tokens.",
    reviewSummary:
      "Documentation scopes remain preview metadata and never touch live provider content.",
  },
  {
    id: "provider-design-desk",
    name: "Design Desk",
    categoryId: "category-design",
    summary: "Design handoff provider preview for review-only interface checks.",
    detail:
      "Design Desk highlights design-file review scopes, status markers, and disabled authorize controls in a local mock catalog.",
    connectionId: "connection-design-desk",
    riskLevel: "medium",
    scopeIds: ["scope-design-read"],
    workspaceNote: "Design review metadata without SDKs or callbacks.",
    connectionSummary: "Syncing preview state only; no provider SDK is loaded.",
    reviewSummary:
      "Design handoff metadata is shown for review while all actions remain inert.",
  },
];

export const MOCK_INTEGRATION_CONNECTIONS: IntegrationConnection[] = [
  {
    id: "connection-repo-mirror",
    providerId: "provider-repo-mirror",
    workspaceId: "workspace-terminalflow",
    status: "connected",
    lastCheckedAt: "Now",
    lastActivityAt: "4 minutes ago",
    scopeIds: ["scope-repo-read", "scope-repo-comments"],
    findingIds: ["finding-integrations-1", "finding-integrations-2"],
    activityEventIds: ["integration-activity-1", "integration-activity-2"],
    actionPreviewIds: [
      "integration-action-connect",
      "integration-action-disconnect",
      "integration-action-sync",
      "integration-action-authorize",
    ],
    riskNote: "Repository access is a local preview only and does not invoke OAuth.",
  },
  {
    id: "connection-team-chat",
    providerId: "provider-team-chat",
    workspaceId: "workspace-terminalflow",
    status: "reviewing",
    lastCheckedAt: "8 minutes ago",
    lastActivityAt: "12 minutes ago",
    scopeIds: ["scope-chat-read"],
    findingIds: ["finding-integrations-3", "finding-integrations-4"],
    activityEventIds: ["integration-activity-3", "integration-activity-4"],
    actionPreviewIds: [
      "integration-action-connect",
      "integration-action-reconnect",
      "integration-action-revoke",
    ],
    riskNote: "Chat provider controls are local review markers only.",
  },
  {
    id: "connection-docs-index",
    providerId: "provider-docs-index",
    workspaceId: "workspace-terminalflow",
    status: "offline",
    lastCheckedAt: "21 minutes ago",
    lastActivityAt: "Yesterday",
    scopeIds: ["scope-docs-read"],
    findingIds: ["finding-integrations-2", "finding-integrations-4"],
    activityEventIds: ["integration-activity-1", "integration-activity-5"],
    actionPreviewIds: [
      "integration-action-connect",
      "integration-action-authorize",
      "integration-action-sync",
    ],
    riskNote: "Offline metadata is retained only in local mock records.",
  },
  {
    id: "connection-design-desk",
    providerId: "provider-design-desk",
    workspaceId: "workspace-terminalflow",
    status: "syncing",
    lastCheckedAt: "Now",
    lastActivityAt: "5 minutes ago",
    scopeIds: ["scope-design-read"],
    findingIds: ["finding-integrations-1", "finding-integrations-3"],
    activityEventIds: ["integration-activity-2", "integration-activity-3"],
    actionPreviewIds: [
      "integration-action-connect",
      "integration-action-reconnect",
      "integration-action-sync",
      "integration-action-authorize",
    ],
    riskNote: "Design provider states are simulated and do not touch external services.",
  },
];

export const MOCK_INTEGRATION_STATUS_SUMMARY = {
  totalProviders: MOCK_INTEGRATION_PROVIDERS.length,
  totalCategories: MOCK_INTEGRATION_PROVIDER_CATEGORIES.length,
  totalScopes: MOCK_INTEGRATION_PERMISSION_SCOPES.length,
  totalConnections: MOCK_INTEGRATION_CONNECTIONS.length,
} as const;

export const MOCK_HOST_CONNECTIONS: HostConnection[] = [
  {
    id: "host-main",
    name: "Primary Linux host",
    host: "calvin@workstation",
    status: "connected",
    environment: "local",
    operatingSystem: "Ubuntu 24.04",
    connectionMethod: "local profile",
    workspaceRoot: "/home/calvin/projects",
    lastCheckedAt: "Just now",
    safetyChecks: [
      {
        id: "main-shell",
        label: "Shell access boundary",
        state: "pass",
        detail: "Local profile only; no remote execution is active.",
      },
      {
        id: "main-creds",
        label: "Credential storage",
        state: "warn",
        detail: "Credential save is disabled in this phase.",
      },
      {
        id: "main-network",
        label: "Network reachability",
        state: "pass",
        detail: "Available on the local workspace network.",
      },
    ],
  },
  {
    id: "host-lab",
    name: "Lab node",
    host: "calvin@lab-box",
    status: "connecting",
    environment: "lab",
    operatingSystem: "Debian 12",
    connectionMethod: "saved preset",
    workspaceRoot: "/srv/workspaces",
    lastCheckedAt: "2 minutes ago",
    safetyChecks: [
      {
        id: "lab-shell",
        label: "Shell access boundary",
        state: "warn",
        detail: "Connection preview only; no host pairing is active.",
      },
      {
        id: "lab-cred",
        label: "Credential handling",
        state: "warn",
        detail: "Save credentials action is disabled.",
      },
      {
        id: "lab-routing",
        label: "Routing scope",
        state: "pass",
        detail: "Represents a static local profile for UI design only.",
      },
    ],
  },
  {
    id: "host-remote",
    name: "Remote staging",
    host: "calvin@staging-node",
    status: "offline",
    environment: "remote",
    operatingSystem: "Fedora 40",
    connectionMethod: "manual setup",
    workspaceRoot: "/opt/staging",
    lastCheckedAt: "12 minutes ago",
    safetyChecks: [
      {
        id: "remote-shell",
        label: "SSH boundary",
        state: "blocked",
        detail: "SSH is intentionally out of scope for this phase.",
      },
      {
        id: "remote-secrets",
        label: "Secret storage",
        state: "blocked",
        detail: "No secret storage or credential vault is wired.",
      },
      {
        id: "remote-ops",
        label: "Remote execution",
        state: "blocked",
        detail: "Command actions remain disabled and local-only.",
      },
    ],
  },
];

export const MOCK_PROJECTS: Project[] = [
  {
    id: "terminalflow",
    name: "TerminalFlow",
    summary: "Mobile control plane for terminal-driven workflows.",
    path: "/home/calvin/projects/TerminalFlow",
    language: "TypeScript",
    hostId: "host-main",
    health: "ready",
    updatedAt: "Today, 9:12 AM",
    openFiles: 4,
  },
  {
    id: "signalops",
    name: "SignalOps",
    summary: "Ops dashboard for service checks and deploy notes.",
    path: "/home/calvin/projects/signalops",
    language: "Go",
    hostId: "host-main",
    health: "ready",
    updatedAt: "Yesterday",
    openFiles: 2,
  },
  {
    id: "edge-notes",
    name: "Edge Notes",
    summary: "Side project for lightweight note capture and search.",
    path: "/srv/workspaces/edge-notes",
    language: "Rust",
    hostId: "host-lab",
    health: "attention",
    updatedAt: "2 days ago",
    openFiles: 6,
  },
];

export const MOCK_SESSIONS: TerminalSession[] = [
  {
    id: "session-hub",
    title: "App shell review",
    projectId: "terminalflow",
    hostId: "host-main",
    state: "running",
    branch: "main",
    lastActivityAt: "Just now",
    cwd: "/home/calvin/projects/TerminalFlow",
    commandPreview: "pnpm typecheck",
    outputPreview: "Type-check is currently green.",
    startedAt: "14 min ago",
  },
  {
    id: "session-api",
    title: "API workspace prep",
    projectId: "signalops",
    hostId: "host-main",
    state: "idle",
    branch: "feature/session-notes",
    lastActivityAt: "8 minutes ago",
    cwd: "/home/calvin/projects/signalops",
    commandPreview: "git status --short",
    outputPreview: "Workspace is clean.",
    startedAt: "1 hr ago",
  },
  {
    id: "session-lab",
    title: "Lab node diagnostics",
    projectId: "edge-notes",
    hostId: "host-lab",
    state: "paused",
    branch: "debug/host-check",
    lastActivityAt: "2 hours ago",
    cwd: "/srv/workspaces/edge-notes",
    commandPreview: "cargo test",
    outputPreview: "Waiting on host connection.",
    startedAt: "3 hr ago",
  },
];

export const MOCK_COMMAND_ENTRIES: CommandEntry[] = [
  {
    id: "command-001",
    sessionId: "session-hub",
    command: "pnpm install",
    status: "completed",
    timestamp: "14 min ago",
    cwd: "/home/calvin/projects/TerminalFlow",
    output: "Dependencies are already in sync.",
  },
  {
    id: "command-002",
    sessionId: "session-hub",
    command: "npm run typecheck",
    status: "completed",
    timestamp: "12 min ago",
    cwd: "/home/calvin/projects/TerminalFlow",
    output: "No type errors found.",
  },
  {
    id: "command-003",
    sessionId: "session-hub",
    command: "pnpm dev",
    status: "draft",
    timestamp: "Now",
    cwd: "/home/calvin/projects/TerminalFlow",
    output: "Composer only. No command execution is active.",
  },
  {
    id: "command-101",
    sessionId: "session-api",
    command: "git status --short",
    status: "completed",
    timestamp: "8 minutes ago",
    cwd: "/home/calvin/projects/signalops",
    output: "Workspace is clean.",
  },
  {
    id: "command-102",
    sessionId: "session-api",
    command: "git branch --show-current",
    status: "completed",
    timestamp: "6 minutes ago",
    cwd: "/home/calvin/projects/signalops",
    output: "feature/session-notes",
  },
  {
    id: "command-201",
    sessionId: "session-lab",
    command: "cargo test",
    status: "blocked",
    timestamp: "2 hours ago",
    cwd: "/srv/workspaces/edge-notes",
    output: "Blocked on host connection; not executed here.",
  },
];

const allowlistedSafetyCheck: CommandSimulationSafetyCheck = {
  id: "sim-safety-allowlisted",
  label: "Allowlisted mock command",
  state: "allowlisted",
  detail: "This command is handled by local static simulation only.",
};

const warningSafetyCheck: CommandSimulationSafetyCheck = {
  id: "sim-safety-warning",
  label: "Local simulation warning",
  state: "warning",
  detail: "The command is safe to preview, but the simulator is returning a cautionary mock state.",
};

const blockedSafetyCheck: CommandSimulationSafetyCheck = {
  id: "sim-safety-blocked",
  label: "Blocked by phase guard",
  state: "blocked",
  detail: "Host, shell, and workflow execution are intentionally out of scope for this phase.",
};

export const MOCK_SIMULATED_COMMAND_PRESETS: SimulatedCommandPreset[] = [
  {
    id: "preset-typecheck",
    label: "Type-check workspace",
    command: "npm run typecheck",
    description: "Allowed mock command that returns a clean local result.",
    status: "completed",
    summary: "The simulator reports a clean type-check with no shell execution.",
    exitCode: 0,
    duration: "1.4s",
    output: {
      stdout: ["> terminalflow@0.2.0 typecheck", "> tsc --noEmit", "No type errors found."],
      stderr: [],
    },
    safetyCheck: allowlistedSafetyCheck,
  },
  {
    id: "preset-status",
    label: "Inspect workspace status",
    command: "git status --short",
    description: "Local preview command that surfaces a cautionary mock state.",
    status: "warning",
    summary: "The simulator shows a warning-style status check with local-only output.",
    exitCode: 0,
    duration: "0.8s",
    output: {
      stdout: ["M app/(tabs)/sessions/[sessionId]/page.tsx", "?? components/session/command-composer.tsx"],
      stderr: ["Mock warning: workspace state is illustrative only."],
    },
    safetyCheck: warningSafetyCheck,
  },
  {
    id: "preset-lint",
    label: "Preview lint failure",
    command: "npm run lint",
    description: "Mock failure state for command review and UI testing.",
    status: "failed",
    summary: "The simulator returns a failed exit code and stderr-style output.",
    exitCode: 1,
    duration: "2.1s",
    output: {
      stdout: ["> terminalflow@0.2.0 lint", "> eslint ."],
      stderr: ["1 problem found in static preview mode."],
    },
    safetyCheck: warningSafetyCheck,
  },
  {
    id: "preset-ssh",
    label: "Blocked host probe",
    command: "ssh staging",
    description: "Intentionally blocked to show the safety explanation path.",
    status: "blocked",
    summary: "The simulator blocks this command and explains why before any result is shown.",
    exitCode: null,
    duration: "--",
    output: {
      stdout: [],
      stderr: [],
    },
    safetyCheck: blockedSafetyCheck,
  },
];

export const MOCK_WORKFLOWS: Workflow[] = [
  {
    id: "workflow-check",
    name: "Preflight checks",
    projectId: "terminalflow",
    trigger: "Manual",
    state: "ready",
    steps: ["typecheck", "lint", "build"],
    lastRunAt: "Today, 8:41 AM",
  },
  {
    id: "workflow-notes",
    name: "Update notes",
    projectId: "edge-notes",
    trigger: "Manual",
    state: "draft",
    steps: ["fetch workspace", "preview files", "summarize changes"],
    lastRunAt: "Not run yet",
  },
  {
    id: "workflow-sync",
    name: "Session sync",
    projectId: "signalops",
    trigger: "On demand",
    state: "blocked",
    steps: ["inspect session", "collect output", "queue follow-up"],
    lastRunAt: "Yesterday, 5:14 PM",
  },
];

export const MOCK_WORKFLOW_RUNS: WorkflowRun[] = [
  {
    id: "run-preflight-001",
    workflowId: "workflow-check",
    workflowName: "Preflight checks",
    projectId: "terminalflow",
    trigger: "Manual",
    target: "TerminalFlow on Primary Linux host",
    targetDetail: "Local workspace planning run only.",
    workspaceRoot: "/home/calvin/projects/TerminalFlow",
    status: "completed",
    safetyState: "safe",
    startTime: "Today, 8:41 AM",
    duration: "3m 42s",
    summary: "The static preflight run finished cleanly after the three planned steps.",
    steps: [
      {
        id: "run-preflight-001-step-1",
        stepId: "step-check-1",
        title: "Type-check workspace",
        kind: "check",
        status: "completed",
        startedAt: "8:41 AM",
        finishedAt: "8:42 AM",
        duration: "48s",
        detail: "Type-check completed with no errors.",
      },
      {
        id: "run-preflight-001-step-2",
        stepId: "step-check-2",
        title: "Run lint review",
        kind: "check",
        status: "completed",
        startedAt: "8:42 AM",
        finishedAt: "8:43 AM",
        duration: "1m 04s",
        detail: "Lint pass completed in preview mode.",
      },
      {
        id: "run-preflight-001-step-3",
        stepId: "step-check-3",
        title: "Build app bundle",
        kind: "command",
        status: "completed",
        startedAt: "8:43 AM",
        finishedAt: "8:45 AM",
        duration: "1m 50s",
        detail: "Build step ended cleanly in the static log surface.",
      },
    ],
    timeline: [
      {
        id: "run-preflight-001-event-1",
        kind: "started",
        time: "8:41 AM",
        title: "Run started",
        detail: "Manual trigger selected from the static builder.",
        index: 1,
      },
      {
        id: "run-preflight-001-event-2",
        kind: "step-started",
        time: "8:41 AM",
        title: "Type-check workspace started",
        detail: "The first workflow step moved into the active lane.",
        stepId: "run-preflight-001-step-1",
        index: 2,
      },
      {
        id: "run-preflight-001-event-3",
        kind: "step-finished",
        time: "8:42 AM",
        title: "Type-check workspace completed",
        detail: "No errors were recorded in the static execution log.",
        stepId: "run-preflight-001-step-1",
        index: 3,
      },
      {
        id: "run-preflight-001-event-4",
        kind: "step-started",
        time: "8:42 AM",
        title: "Run lint review started",
        detail: "Second step previewed as the run advanced.",
        stepId: "run-preflight-001-step-2",
        index: 4,
      },
      {
        id: "run-preflight-001-event-5",
        kind: "step-finished",
        time: "8:43 AM",
        title: "Run lint review completed",
        detail: "Lint review returned to the completed lane.",
        stepId: "run-preflight-001-step-2",
        index: 5,
      },
      {
        id: "run-preflight-001-event-6",
        kind: "step-started",
        time: "8:43 AM",
        title: "Build app bundle started",
        detail: "Build step entered the final phase of the run.",
        stepId: "run-preflight-001-step-3",
        index: 6,
      },
      {
        id: "run-preflight-001-event-7",
        kind: "completed",
        time: "8:45 AM",
        title: "Run completed",
        detail: "Workflow execution is static; this completion state is mock data only.",
        index: 7,
      },
    ],
    logs: [
      {
        id: "run-preflight-001-log-1",
        time: "8:41 AM",
        level: "info",
        stream: "stdout",
        message: "Starting preflight checks in static preview mode.",
      },
      {
        id: "run-preflight-001-log-2",
        time: "8:41 AM",
        level: "stdout",
        stream: "stdout",
        message: "[step 1] npm run typecheck",
        stepId: "run-preflight-001-step-1",
      },
      {
        id: "run-preflight-001-log-3",
        time: "8:42 AM",
        level: "stdout",
        stream: "stdout",
        message: "[step 1] No type errors found.",
        stepId: "run-preflight-001-step-1",
      },
      {
        id: "run-preflight-001-log-4",
        time: "8:42 AM",
        level: "stdout",
        stream: "stdout",
        message: "[step 2] npm run lint",
        stepId: "run-preflight-001-step-2",
      },
      {
        id: "run-preflight-001-log-5",
        time: "8:43 AM",
        level: "stdout",
        stream: "stdout",
        message: "[step 3] npm run build",
        stepId: "run-preflight-001-step-3",
      },
      {
        id: "run-preflight-001-log-6",
        time: "8:45 AM",
        level: "info",
        stream: "stdout",
        message: "Static run marked completed. No workflow runner was used.",
      },
    ],
  },
  {
    id: "run-preflight-002",
    workflowId: "workflow-check",
    workflowName: "Preflight checks",
    projectId: "terminalflow",
    trigger: "Manual",
    target: "TerminalFlow on Primary Linux host",
    targetDetail: "Same run target, interrupted after safety review.",
    workspaceRoot: "/home/calvin/projects/TerminalFlow",
    status: "cancelled",
    safetyState: "warning",
    startTime: "Yesterday, 4:02 PM",
    duration: "1m 12s",
    summary: "The static run was cancelled after a safety interruption was surfaced.",
    steps: [
      {
        id: "run-preflight-002-step-1",
        stepId: "step-check-1",
        title: "Type-check workspace",
        kind: "check",
        status: "completed",
        startedAt: "4:02 PM",
        finishedAt: "4:03 PM",
        duration: "44s",
        detail: "Initial validation completed before interruption.",
      },
      {
        id: "run-preflight-002-step-2",
        stepId: "step-check-2",
        title: "Run lint review",
        kind: "check",
        status: "cancelled",
        startedAt: "4:03 PM",
        finishedAt: "4:03 PM",
        duration: "0s",
        detail: "Stopped because the run was cancelled in static preview.",
      },
      {
        id: "run-preflight-002-step-3",
        stepId: "step-check-3",
        title: "Build app bundle",
        kind: "command",
        status: "queued",
        startedAt: "Not started",
        finishedAt: "Not started",
        duration: "--",
        detail: "Never reached because the run was cancelled.",
      },
    ],
    timeline: [
      {
        id: "run-preflight-002-event-1",
        kind: "started",
        time: "4:02 PM",
        title: "Run started",
        detail: "Manual rerun launched from the workflow detail surface.",
        index: 1,
      },
      {
        id: "run-preflight-002-event-2",
        kind: "step-started",
        time: "4:02 PM",
        title: "Type-check workspace started",
        detail: "First step advanced normally.",
        stepId: "run-preflight-002-step-1",
        index: 2,
      },
      {
        id: "run-preflight-002-event-3",
        kind: "step-finished",
        time: "4:03 PM",
        title: "Type-check workspace completed",
        detail: "Static log captured the first step completion.",
        stepId: "run-preflight-002-step-1",
        index: 3,
      },
      {
        id: "run-preflight-002-event-4",
        kind: "interrupted",
        time: "4:03 PM",
        title: "Safety interruption",
        detail: "The run was paused and then cancelled in the mock timeline.",
        index: 4,
      },
      {
        id: "run-preflight-002-event-5",
        kind: "cancelled",
        time: "4:03 PM",
        title: "Run cancelled",
        detail: "No further steps were scheduled after cancellation.",
        index: 5,
      },
    ],
    logs: [
      {
        id: "run-preflight-002-log-1",
        time: "4:02 PM",
        level: "info",
        stream: "stdout",
        message: "Run resumed from history for static inspection.",
      },
      {
        id: "run-preflight-002-log-2",
        time: "4:03 PM",
        level: "warn",
        stream: "stderr",
        message: "Safety interruption surfaced; the run will not continue.",
      },
      {
        id: "run-preflight-002-log-3",
        time: "4:03 PM",
        level: "error",
        stream: "stderr",
        message: "Cancellation recorded in static state only.",
      },
    ],
  },
  {
    id: "run-sync-001",
    workflowId: "workflow-sync",
    workflowName: "Session sync",
    projectId: "signalops",
    trigger: "On demand",
    target: "SignalOps on Primary Linux host",
    targetDetail: "Blocked preview target showing a safety stop.",
    workspaceRoot: "/home/calvin/projects/signalops",
    status: "blocked",
    safetyState: "blocked",
    startTime: "Today, 9:08 AM",
    duration: "26s",
    summary: "The sync run was blocked at the safety boundary before any command-like activity.",
    steps: [
      {
        id: "run-sync-001-step-1",
        stepId: "step-sync-1",
        title: "Inspect session context",
        kind: "check",
        status: "blocked",
        startedAt: "9:08 AM",
        finishedAt: "9:08 AM",
        duration: "12s",
        detail: "Blocked before the session context could be collected.",
      },
      {
        id: "run-sync-001-step-2",
        stepId: "step-sync-2",
        title: "Collect output",
        kind: "decision",
        status: "blocked",
        startedAt: "Not started",
        finishedAt: "Not started",
        duration: "--",
        detail: "Blocked by the static safety guard.",
      },
      {
        id: "run-sync-001-step-3",
        stepId: "step-sync-3",
        title: "Queue follow-up",
        kind: "handoff",
        status: "queued",
        startedAt: "Not started",
        finishedAt: "Not started",
        duration: "--",
        detail: "Queued only in appearance; no background job exists.",
      },
    ],
    timeline: [
      {
        id: "run-sync-001-event-1",
        kind: "started",
        time: "9:08 AM",
        title: "Run started",
        detail: "Static blocked run entered the timeline.",
        index: 1,
      },
      {
        id: "run-sync-001-event-2",
        kind: "step-started",
        time: "9:08 AM",
        title: "Inspect session context started",
        detail: "The first step attempted to begin.",
        stepId: "run-sync-001-step-1",
        index: 2,
      },
      {
        id: "run-sync-001-event-3",
        kind: "interrupted",
        time: "9:08 AM",
        title: "Safety boundary reached",
        detail: "Host execution is not active, so the run was blocked.",
        index: 3,
      },
      {
        id: "run-sync-001-event-4",
        kind: "cancelled",
        time: "9:08 AM",
        title: "Run blocked",
        detail: "No workflow runner or queue handled the event.",
        index: 4,
      },
    ],
    logs: [
      {
        id: "run-sync-001-log-1",
        time: "9:08 AM",
        level: "info",
        stream: "stdout",
        message: "Session sync preview opened in static mode.",
      },
      {
        id: "run-sync-001-log-2",
        time: "9:08 AM",
        level: "warn",
        stream: "stderr",
        message: "Host execution inactive; blocking further progress.",
        stepId: "run-sync-001-step-1",
      },
      {
        id: "run-sync-001-log-3",
        time: "9:08 AM",
        level: "error",
        stream: "stderr",
        message: "No runner, queue, or background job is attached.",
      },
    ],
  },
];

export const MOCK_WORKSPACE = {
  name: "Calvin's workspace",
  root: "/home/calvin/projects",
  hostConnectionCount: MOCK_HOST_CONNECTIONS.length,
  connectedHosts: MOCK_HOST_CONNECTIONS.filter((host) => host.status === "connected")
    .length,
  projectCount: MOCK_PROJECTS.length,
  runningSessions: MOCK_SESSIONS.filter((session) => session.state === "running").length,
  workflowCount: MOCK_WORKFLOWS.length,
  workflowRunCount: MOCK_WORKFLOW_RUNS.length,
} as const;
